ReferenceClass.cpp
string Stos(String^k)
Referenced by ReferenceClass::ref_Post::AssemblyPartT2C, ReferenceClass::ref_Post::ConvertRefPost, ReferenceClass::ref_Pre::GetTransCADName_from_buffer, ReferenceClass::ref_Pre::Parsing, ReferenceClass::ref_Pre::TestEnvironment.
String stoS(string k)
Referenced by ReferenceClass::ref_Post::ConvertRefPost, ReferenceClass::ref_Pre::GetTransCADName_from_buffer.
std::string replace_all(__in const std::string &message, __in const std::string &pattern, __in const std::string &replace)
Referenced by ReferenceClass::ref_Pre::TestEnvironment.