Pre::ReferenceEntity
Part* Pre::ReferenceEntity::_pPart
Referenced by GetBasicFaceName, GetInfo, GetReferName, ReferenceEntity, ToTransCAD.
string Pre::ReferenceEntity::name
Referenced by GetName, ReferenceEntity.
string Pre::ReferenceEntity::feature
Referenced by GetFeatureName, GetInfo, GetReferName, ToTransCAD.
string Pre::ReferenceEntity::axis
Referenced by GetAxisName.
int Pre::ReferenceEntity::type
Referenced by GetFullFaceName, GetInfo, GetReferenceType, GetReferName, ReferenceEntity, ToTransCAD.
string Pre::ReferenceEntity::TransCADFaceName
Referenced by GetInfo, GetReferName, ToTransCAD.
string Pre::ReferenceEntity::TransCADEdgeName
Referenced by GetInfo, GetReferName, ToTransCAD.
TransCAD::IReferencePtr Pre::ReferenceEntity::spReferencePtr
Referenced by GetReferencePtr, ToTransCAD.
FSketch* Pre::ReferenceEntity::pSketchManager
Referenced by GetBasicFaceName, GetInfo, GetReferName, ReferenceEntity.
FaceInfoList Pre::ReferenceEntity::pFace
Referenced by GetBasicFaceName, GetFaceInfo, GetFullFaceName.
EdgeInfo Pre::ReferenceEntity::pEdge
Referenced by GetEdgeInfo, GetFullFaceName.
WireInfo Pre::ReferenceEntity::pWire
Referenced by GetInfo, GetReferName, GetWireInfo.
Pre::ReferenceEntity::ReferenceEntity(Part *pPart, int type, string name)
References _pPart, name, pSketchManager, type.
string Pre::ReferenceEntity::GetReferName(char *&context)
References _pPart, WireInfo::_sketchItemName, WireInfo::_sketchName, feature, Pre::Part::GetFeatureByName, GetFullFaceName, pSketchManager, pWire, TransCADEdgeName, TransCADFaceName, type.
Referenced by ReferenceClass::ref_Pre::GetTransCADName_from_buffer.
Pre::ReferenceEntity::~ReferenceEntity(void)
void Pre::ReferenceEntity::GetInfo(ifstream &is)
References _pPart, WireInfo::_sketchItemName, WireInfo::_sketchName, feature, Pre::Part::GetFeatureByName, GetFullFaceName, pSketchManager, pWire, TransCADEdgeName, TransCADFaceName, type.
Referenced by Pre::Part::CreateReferenceEntity.
void Pre::ReferenceEntity::ToTransCAD()
References _pPart, Pre::Part::_spPart, feature, spReferencePtr, TransCADEdgeName, TransCADFaceName, type.
Referenced by Pre::FSketch::ToTransCAD.
virtual int Pre::ReferenceEntity::GetReferenceType()
References type.
Referenced by Pre::FeatureSOLIDCreatePatternRectangular::Modify, Pre::FeatureSOLIDCreatePatternCircular::Modify.
virtual string Pre::ReferenceEntity::GetName()
References name.
Referenced by Pre::Part::GetReferenceEntityByName.
virtual string Pre::ReferenceEntity::GetFeatureName()
References feature.
Referenced by Pre::FeatureSOLIDCreateSweep::GetInfo, Pre::FDatumPlaneOffset::GetInfo, Pre::FeatureSOLIDCreateRevolve::GetInfo, Pre::FeatureSOLIDCreateExtrude::GetInfo, Pre::FeatureSOLIDCreateSweep::Modify, Pre::FeatureSOLIDCreateRevolve::Modify, Pre::FeatureSOLIDCreateExtrude::Modify, Pre::FeatureSOLIDCreatePatternRectangular::SetDirection, Pre::FeatureSOLIDCreatePatternCircular::SetDirection.
virtual string Pre::ReferenceEntity::GetAxisName()
References axis.
virtual TransCAD::IReferencePtr Pre::ReferenceEntity::GetReferencePtr()
References spReferencePtr.
FaceInfoList Pre::ReferenceEntity::GetFaceInfo()
References pFace.
Referenced by Pre::FeatureSOLIDCreatePatternCircular::SetDirection.
EdgeInfo Pre::ReferenceEntity::GetEdgeInfo()
References pEdge.
WireInfo Pre::ReferenceEntity::GetWireInfo()
References pWire.
Referenced by Pre::FeatureSOLIDCreateRevolve::AddNewRevolveAxis.
string Pre::ReferenceEntity::GetFullFaceName(char *&buffer)
References GetBasicFaceName, pEdge, pFace, type.
Referenced by GetInfo, GetReferName.
string Pre::ReferenceEntity::GetBasicFaceName(char *&buffer)
References FaceInfo::_featureName, FaceInfo::_featureType, _pPart, FaceInfo::_sketchItemName1, FaceInfo::_sketchItemName2, FaceInfo::_sketchName1, FaceInfo::_sketchName2, Pre::Part::GetFeatureByName, pFace, pSketchManager.
Referenced by GetFullFaceName.