Post::Vector3D
double Post::Vector3D::_x
Referenced by Norm, operator*, operator+, operator-, operator/, operator=, operator==, operator[], operator^, SetXYZ, Size, X.
double Post::Vector3D::_y
Referenced by Norm, operator*, operator+, operator-, operator/, operator=, operator==, operator^, SetXYZ, Size, Y.
double Post::Vector3D::_z
Referenced by Norm, operator*, operator+, operator-, operator/, operator=, operator==, operator^, SetXYZ, Size, Z.
Post::Vector3D::Vector3D(void)
Referenced by Norm, operator*, operator+, operator-, operator/, operator^.
Post::Vector3D::Vector3D(double x, double y, double z)
Post::Vector3D::Vector3D(double coord[])
double Post::Vector3D::X(void) const
References _x.
double Post::Vector3D::Y(void) const
References _y.
double Post::Vector3D::Z(void) const
References _z.
void Post::Vector3D::X(double x)
References _x.
void Post::Vector3D::Y(double y)
References _y.
void Post::Vector3D::Z(double z)
References _z.
void Post::Vector3D::SetXYZ(double x, double y, double z)
References _x, _y, _z.
void Post::Vector3D::SetXYZ(double rhs[3])
References _x, _y, _z.
double& Post::Vector3D::operator[](int i)
References _x.
Vector3D Post::Vector3D::operator+(const Vector3D &rhs)
References _x, _y, _z, Vector3D.
Vector3D Post::Vector3D::operator-(const Vector3D &rhs)
References _x, _y, _z, Vector3D.
Vector3D Post::Vector3D::operator*(double d)
References _x, _y, _z, Vector3D.
Vector3D Post::Vector3D::operator/(double d)
References _x, _y, _z, Vector3D.
double Post::Vector3D::operator*(Vector3D &d)
References _x, _y, _z.
Vector3D Post::Vector3D::operator^(Vector3D &d)
References _x, _y, _z, Vector3D.
bool Post::Vector3D::operator==(const Vector3D &rhs)
References _x, _y, _z.
void Post::Vector3D::operator=(const Vector3D &rhs)
References _x, _y, _z.
double Post::Vector3D::Size() const
References _x, _y, _z.
Referenced by Norm.
Vector3D Post::Vector3D::Norm(void)
References _x, _y, _z, Size, Vector3D.