Post::Feature
Part* Post::Feature::_pPart
Referenced by Feature, GetPart, Post::FSketch::ToCATIA.
size_t Post::Feature::_nIndex
Referenced by Feature, GetFeatureIndex.
string Post::Feature::_strName
Referenced by Feature, GetFeatureName, SetFeatureName.
TransCAD::IFeaturePtr Post::Feature::_spFeature
Referenced by Feature, Post::FSketch::FSketch, GetTransCADFeature, Post::FeatureSOLIDCreateFilletConstant::ToCATIA, Post::FDatumPlaneOffset::ToCATIA, Post::FeatureSOLIDCreateChamfer::ToCATIA, Post::FeatureSOLIDCreatePatternCircular::ToCATIA, Post::FeatureSOLIDCreatePatternRectangular::ToCATIA, Post::FeatureSOLIDCreateCutExtrude::ToCATIA, Post::FeatureSOLIDCreateProtrusionExtrude::ToCATIA, Post::FeatureSOLIDCreateCutRevolve::ToCATIA, Post::FeatureSOLIDCreateProtrusionRevolve::ToCATIA, Post::FeatureSOLIDCreateSectionsLoft::ToCATIA, Post::FeatureSOLIDCreateProtrusionLoft::ToCATIA, Post::FeatureSOLIDCreateFacesLoft::ToCATIA, Post::FeatureSOLIDCreateProtrusionSweep::ToCATIA.
Post::Feature::Feature(Part *pPart, TransCAD::IFeaturePtr spFeature)
References _nIndex, _pPart, _spFeature, _strName, Post::Part::GetSize.
Post::Feature::~Feature(void)
Part* Post::Feature::GetPart()
References _pPart.
Referenced by Post::FeatureSOLIDCreateCutExtrude::GetInfo, Post::FeatureSOLIDCreateCutRevolve::GetInfo, Post::FeatureSOLIDCreateProtrusionExtrude::GetInfo, Post::FeatureSOLIDCreateProtrusionRevolve::GetInfo, Post::FeatureSOLIDCreateProtrusionSweep::GetInfo, Post::FeatureSOLIDCreateHoleCounterbored::ToCATIA, Post::FeatureSOLIDCreateHoleCountersunk::ToCATIA, Post::FeatureSOLIDCreateChamfer::ToCATIA, Post::FeatureSOLIDCreatePatternCircular::ToCATIA, Post::FeatureSOLIDCreatePatternRectangular::ToCATIA, Post::FDatumPlaneOffset::ToCATIA, Post::FeatureSOLIDCreateFilletConstant::ToCATIA, Post::FeatureSOLIDCreateProtrusionRevolve::ToCATIA, Post::FeatureSOLIDCreateCutExtrude::ToCATIA, Post::FeatureSOLIDCreateProtrusionExtrude::ToCATIA, Post::FeatureSOLIDCreateCutRevolve::ToCATIA, Post::FeatureSOLIDCreateProtrusionSweep::ToCATIA, Post::FeatureSOLIDCreateSectionsLoft::ToCATIA, Post::FSketch::ToCATIA.
void Post::Feature::SetFeatureName(string featureName)
References _strName.
size_t Post::Feature::GetFeatureIndex()
References _nIndex.
string Post::Feature::GetFeatureName()
References _strName.
Referenced by Post::Part::GetFeatureByName, Post::FDatumPlane::GetInfo, Post::FSketch::GetInfo, Post::FDatumPlane::ToCATIA.
TransCAD::IFeaturePtr Post::Feature::GetTransCADFeature()
References _spFeature.
Referenced by Post::FDatumPlaneOffset::GetInfo, Post::FeatureSOLIDCreateChamfer::GetInfo, Post::FeatureSOLIDCreateFilletConstant::GetInfo, Post::FeatureSOLIDCreateHoleCounterbored::GetInfo, Post::FeatureSOLIDCreateHoleCountersunk::GetInfo, Post::FeatureSOLIDCreatePatternCircular::GetInfo, Post::FeatureSOLIDCreatePatternRectangular::GetInfo, Post::FeatureSOLIDCreateProtrusionRevolve::GetInfo, Post::FeatureSOLIDCreateCutRevolve::GetInfo, Post::FeatureSOLIDCreateCutExtrude::GetInfo, Post::FeatureSOLIDCreateProtrusionExtrude::GetInfo, Post::FeatureSOLIDCreateProtrusionLoft::GetInfo, Post::FeatureSOLIDCreateProtrusionSweep::GetInfo, Post::FeatureSOLIDCreateSectionsLoft::GetInfo, Post::SKETCHCreate2DCenterline::GetInfo, Post::FeatureSOLIDCreateFacesLoft::GetInfo, Post::SKETCHCreate2DPoint::GetInfo, Post::SKETCHCreate2DCircleCenterPoint::GetInfo, Post::SKETCHCreate2DLine2Points::GetInfo, Post::SKETCHCreate2DCircularArc::GetInfo, Post::FeatureSOLIDCreateProtrusionExtrude::ToCATIA, Post::FeatureSOLIDCreateCutExtrude::ToCATIA, Post::FeatureSOLIDCreateProtrusionRevolve::ToCATIA, Post::FeatureSOLIDCreateCutRevolve::ToCATIA, Post::FeatureSOLIDCreateProtrusionLoft::ToCATIA, Post::FeatureSOLIDCreateProtrusionSweep::ToCATIA, Post::FeatureSOLIDCreateFacesLoft::ToCATIA, Post::SKETCHCreate2DCenterline::ToCATIA, Post::SKETCHCreate2DPoint::ToCATIA, Post::FSketch::ToCATIA, Post::SKETCHCreate2DLine2Points::ToCATIA, Post::SKETCHCreate2DCircleCenterPoint::ToCATIA, Post::SKETCHCreate2DCircularArc::ToCATIA.
virtual void Post::Feature::GetInfo()
virtual void Post::Feature::ToCATIA()
virtual double Post::Feature::GetStartDepth()
virtual double Post::Feature::GetEndDepth()