Pre::FeatureSOLIDCreatePatternCircular
bstr_t Pre::FeatureSOLIDCreatePatternCircular::_spTargetFeature
Referenced by GetInfo, ToTransCAD.
double Pre::FeatureSOLIDCreatePatternCircular::CircleSpacing
Referenced by CheckAttribute, FeatureSOLIDCreatePatternCircular, GetInfo, ToTransCAD.
double Pre::FeatureSOLIDCreatePatternCircular::OrgX
Referenced by FeatureSOLIDCreatePatternCircular, SetDirection, ToTransCAD.
double Pre::FeatureSOLIDCreatePatternCircular::OrgY
Referenced by FeatureSOLIDCreatePatternCircular, SetDirection, ToTransCAD.
double Pre::FeatureSOLIDCreatePatternCircular::OrgZ
Referenced by FeatureSOLIDCreatePatternCircular, SetDirection, ToTransCAD.
int Pre::FeatureSOLIDCreatePatternCircular::CircleNumber
Referenced by CheckAttribute, FeatureSOLIDCreatePatternCircular, GetInfo, ToTransCAD.
double Pre::FeatureSOLIDCreatePatternCircular::AngularSpacing
Referenced by CheckAttribute, FeatureSOLIDCreatePatternCircular, GetInfo, ToTransCAD.
double Pre::FeatureSOLIDCreatePatternCircular::DirX
Referenced by FeatureSOLIDCreatePatternCircular, Modify, SetDirection, ToTransCAD.
double Pre::FeatureSOLIDCreatePatternCircular::DirY
Referenced by FeatureSOLIDCreatePatternCircular, Modify, SetDirection, ToTransCAD.
double Pre::FeatureSOLIDCreatePatternCircular::DirZ
Referenced by FeatureSOLIDCreatePatternCircular, Modify, SetDirection, ToTransCAD.
int Pre::FeatureSOLIDCreatePatternCircular::AngularNumber
Referenced by CheckAttribute, FeatureSOLIDCreatePatternCircular, GetInfo, ToTransCAD.
string Pre::FeatureSOLIDCreatePatternCircular::_RefPlane
Referenced by Modify, ToTransCAD.
string Pre::FeatureSOLIDCreatePatternCircular::_rotationAxis
Referenced by Modify.
vector<ReferenceEntity *> Pre::FeatureSOLIDCreatePatternCircular::_referenceEntityList
Pre::FeatureSOLIDCreatePatternCircular::FeatureSOLIDCreatePatternCircular(Part *pPart, int type, string name)
References AngularNumber, AngularSpacing, CircleNumber, CircleSpacing, DirX, DirY, DirZ, OrgX, OrgY, OrgZ.
Pre::FeatureSOLIDCreatePatternCircular::~FeatureSOLIDCreatePatternCircular()
void Pre::FeatureSOLIDCreatePatternCircular::GetInfo(ifstream &is)
References _spTargetFeature, AngularNumber, AngularSpacing, CircleNumber, CircleSpacing.
void Pre::FeatureSOLIDCreatePatternCircular::ToTransCAD()
References Pre::Feature::_name, _RefPlane, Pre::Part::_spFeatures, Pre::Part::_spPart, _spTargetFeature, AngularNumber, AngularSpacing, CircleNumber, CircleSpacing, DirX, DirY, DirZ, Pre::Feature::GetPart, OrgX, OrgY, OrgZ, SetDirection.
void Pre::FeatureSOLIDCreatePatternCircular::CheckAttribute(string name, double value, int type)
References AngularNumber, AngularSpacing, CircleNumber, CircleSpacing.
void Pre::FeatureSOLIDCreatePatternCircular::Modify(char *buffer)
References Pre::Feature::_pPart, _RefPlane, _rotationAxis, Pre::Feature::_type, DirX, DirY, DirZ, Pre::Part::GetReferenceEntityByName, Pre::ReferenceEntity::GetReferenceType.
void Pre::FeatureSOLIDCreatePatternCircular::SetDirection(string refplane)
References Pre::Feature::_pPart, CreateAxis, DirX, DirY, DirZ, Pre::FSKETCHCreate2DCircleCenterPoint::GetCenterPoint, Pre::ReferenceEntity::GetFaceInfo, Pre::Part::GetFeatureByName, Pre::ReferenceEntity::GetFeatureName, Pre::Feature::GetPart, Pre::Part::GetReferenceEntityByName, Pre::FSketch::GetSketchItemFromName, OrgX, OrgY, OrgZ.
Referenced by ToTransCAD.
void Pre::FeatureSOLIDCreatePatternCircular::CreateAxis(FSketch *pRefSketch, FSketch *pRevSketch, Point3D origin, Point3D direction)
References Pre::FSketch::sketchCoord, TransformAxis.
Referenced by SetDirection.
void Pre::FeatureSOLIDCreatePatternCircular::TransformAxis(double refSketCSYS[9], double revSketCSYS[9], Point3D &coords)
References TransformCoordinates.
Referenced by CreateAxis.
void Pre::FeatureSOLIDCreatePatternCircular::TransformCoordinates(double sourceCSYS[3][3], double targetCSYS[3][3], Point3D &coords)
Referenced by TransformAxis.