Pre::Feature
Part* Pre::Feature::_pPart
Referenced by Pre::FeatureSOLIDCreateHole::GetInfo, Pre::FeatureSOLIDCreateChamfer::GetInfo, Pre::FeatureSOLIDCreateFilletConstant::GetInfo, Pre::FeatureSOLIDCreateRevolve::GetInfo, Pre::FeatureSOLIDCreateExtrude::GetInfo, Pre::FSketch::GetInfo, GetPart, Pre::FeatureSOLIDCreatePatternRectangular::Modify, Pre::FeatureSOLIDCreatePatternCircular::Modify, Pre::FeatureSOLIDCreateChamfer::Modify, Pre::FeatureSOLIDCreateFilletConstant::Modify, Pre::FeatureSOLIDCreateRevolve::Modify, Pre::FeatureSOLIDCreateExtrude::Modify, Pre::FeatureSOLIDCreatePatternRectangular::SetDirection, Pre::FeatureSOLIDCreatePatternCircular::SetDirection.
string Pre::Feature::_name
Referenced by Pre::FeatureSOLIDCreateRevolve::AddNewRevolveAxis, GetFeatureName, Pre::FSketch::GetSketchItemInfo, SetFeatureName, Pre::FeatureSOLIDCreateSweep::ToTransCAD, Pre::FDatumPlaneOffset::ToTransCAD, Pre::FeatureSOLIDCreateHole::ToTransCAD, Pre::FeatureSOLIDCreatePatternRectangular::ToTransCAD, Pre::FeatureSOLIDCreateChamfer::ToTransCAD, Pre::FeatureSOLIDCreatePatternCircular::ToTransCAD, Pre::FeatureSOLIDCreateRevolve::ToTransCAD, Pre::FeatureSOLIDCreateFilletConstant::ToTransCAD, Pre::FeatureSOLIDCreateExtrude::ToTransCAD.
int Pre::Feature::_type
Referenced by GetFeatureType, Pre::FeatureSOLIDCreatePatternRectangular::Modify, Pre::FeatureSOLIDCreatePatternCircular::Modify, Pre::FeatureSOLIDCreateExtrude::Modify, SetFeatureType, Pre::FeatureSOLIDCreateSweep::ToTransCAD, Pre::FeatureSOLIDCreateRevolve::ToTransCAD, Pre::FeatureSOLIDCreateExtrude::ToTransCAD.
Pre::Feature::Feature(Part *pPart, int type, string name)
Pre::Feature::~Feature(void)
Part* Pre::Feature::GetPart()
References _pPart.
Referenced by Pre::FeatureSOLIDCreateRevolve::AddNewRevolveAxis, Pre::FeatureSOLIDCreateSweep::GetInfo, Pre::FDatumPlaneOffset::GetInfo, Pre::FeatureSOLIDCreateRevolve::GetInfo, Pre::FeatureSOLIDCreateExtrude::GetInfo, Pre::FeatureSOLIDCreateSweep::Modify, Pre::FeatureSOLIDCreateRevolve::Modify, Pre::FeatureSOLIDCreateExtrude::Modify, Pre::FeatureSOLIDCreatePatternCircular::SetDirection, Pre::FeatureSOLIDCreateSweep::ToTransCAD, Pre::FeatureSOLIDCreatePatternRectangular::ToTransCAD, Pre::FeatureSOLIDCreateHole::ToTransCAD, Pre::FDatumPlaneOffset::ToTransCAD, Pre::FeatureSOLIDCreatePatternCircular::ToTransCAD, Pre::FeatureSOLIDCreateChamfer::ToTransCAD, Pre::FeatureSOLIDCreateFilletConstant::ToTransCAD, Pre::FeatureSOLIDCreateRevolve::ToTransCAD, Pre::FeatureSOLIDCreateExtrude::ToTransCAD, Pre::FSketch::ToTransCAD.
string Pre::Feature::GetFeatureName()
References _name.
Referenced by Pre::Part::GetFeatureByName, Pre::FeatureSOLIDCreateSweep::GetInfo, Pre::FeatureSOLIDCreateRevolve::GetInfo, Pre::FeatureSOLIDCreateExtrude::GetInfo, Pre::FeatureSOLIDCreateSweep::Modify, Pre::FeatureSOLIDCreateRevolve::Modify, Pre::FeatureSOLIDCreateExtrude::Modify, Pre::FeatureSOLIDCreateSweep::ToTransCAD, Pre::FeatureSOLIDCreateRevolve::ToTransCAD, Pre::FeatureSOLIDCreateExtrude::ToTransCAD, Pre::FSketch::ToTransCAD.
int Pre::Feature::GetFeatureType() const
References _type.
void Pre::Feature::SetFeatureName(string featureName)
References _name.
void Pre::Feature::SetFeatureType(int featureType)
References _type.
virtual void Pre::Feature::GetInfo(ifstream &is)
Referenced by Pre::Part::CreateFeature.
virtual void Pre::Feature::ToTransCAD()
Referenced by Pre::Part::ToTransCAD.
void Pre::Feature::CheckAttribute(string name, double value, int type)
Referenced by Pre::AttAngularRepartation::CheckAttribute, Pre::AttLimit::CheckAttribute, Pre::AttLinearRepartation::CheckAttribute, Pre::AttLimit::Modify, Pre::AttParameter::Modify, Pre::AttLength::Modify, Pre::AttAngle::Modify.
void Pre::Feature::Modify(char *buffer)
Referenced by Pre::Part::GetInfo.