ReferenceClass::ref_Post
Post::CATIAReferenceManager* ReferenceClass::ref_Post::m_pReferenceManager
Referenced by ~ref_Post.
ReferenceClass::ref_Post::ref_Post()
ReferenceClass::ref_Post::~ref_Post()
Constructor(持失切) : Connect with C++ Dll.
References m_pReferenceManager.
refCommand ReferenceClass::ref_Post::ConvertRefPost(refCommand w)
Destructor(社瑚切)
References refCommand::command, g_spApplication, GetConstType, refCommand::MasterPart, refCommand::MasterPart_Ref, refCommand::param, refCommand::SlavePart, refCommand::SlavePart_Ref, Stos, stoS, T2C_ReferenceName_From_Assembly.
void ReferenceClass::ref_Post::AssemblyPartT2C(int CompNum, int PartNum, String^path)
References Post::Part::ExternModeToggle, Post::g_pRefManager, g_spApplication, Post::Part::GetInfo, Post::Part::InitReferManager, Stos, Post::Part::ToCATIA.
int ReferenceClass::ref_Post::GetPartNum_From_PartName(TransCAD::ICompPtr u_spComp, string PartName)
Referenced by T2C_ReferenceName_From_Assembly.
int ReferenceClass::ref_Post::GetProductNum_From_SubAssemName(TransCAD::IAssemPtr u_spAssem, string SubAssemName)
Referenced by T2C_ReferenceName_From_Assembly.
string ReferenceClass::ref_Post::T2C_ReferenceName_From_Part(TransCAD::ICompPtr u_spComp, int partNum, string persistentName)
References Post::CATIAReferenceManager::ConvertToBRepFace, Post::Part::ExternModeToggle, Post::g_pRefManager, Post::Part::GetInfo, Post::Part::InitReferManager.
Referenced by T2C_ReferenceName_From_Assembly.
string ReferenceClass::ref_Post::T2C_ReferenceName_From_Assembly(TransCAD::IAssemPtr u_spAssem, int constype, string Pack, string PartName, string assembly_persistentName)
References GetPartNum_From_PartName, GetProductNum_From_SubAssemName, T2C_ReferenceName_From_Part.
Referenced by ConvertRefPost.
String ReferenceClass::ref_Post::GetConstType(int type)
Referenced by ConvertRefPost.