PreStack
List<String^> PreStack::_dir
List<String^> PreStack::_part_catia_name
List<String^> PreStack::_part_transcad_name
void PreStack::StackItem(String^dir, String^part_catia_name, String^part_transcad_name)
int PreStack::GetSize()
Referenced by ReferenceClass::ref_Pre::TestEnvironment.
void PreStack::Clear()
int PreStack::Getindex_from_name(String^part_catia_name, int order)
Referenced by ReferenceClass::ref_Pre::GetTransCADName_from_buffer.
String PreStack::Getitem_from_index(int item, int index)
Referenced by ReferenceClass::ref_Pre::GetTransCADName_from_buffer, ReferenceClass::ref_Pre::TestEnvironment.