Post::Part
FILE* Post::Part::file
Referenced by Part, Pre::Part::Part, ~Part.
TransCAD::IDocsPtr Post::Part::_spDocuments
TransCAD::IPartDocumentPtr Post::Part::_spDocument
Referenced by Pre::Part::Part, ~Part.
TransCAD::IPartPtr Post::Part::_spPart
Referenced by Part, Pre::Part::Part, ~Part.
TransCAD::IFeaturesPtr Post::Part::_spFeatures
Referenced by GetInfo, Part, Pre::Part::Part, Post::FSketch::ToCATIA, ~Part.
string Post::Part::_strPartName
Referenced by GetPartName, Part, Pre::Part::Part.
vector<Feature*> Post::Part::_featureList
Referenced by Clear, CreateFeature, GetFeature, GetSize.
Post::Part::Part()
Post::Part::Part::Part(string fileName)
Post::Part::Part(TransCAD::IPartPtr _p, string fileName)
References _spFeatures, _spPart, _strPartName, file.
Post::Part::Part(TransCAD::IPartPtr _p, int f)
References _spFeatures, _spPart.
Post::Part::~Part(void)
References _spDocument, _spFeatures, _spPart, Clear, file, Post::g_spApplication.
void Post::Part::Clear()
References _featureList.
Referenced by ~Part.
string Post::Part::GetPartName() const
References _strPartName.
Feature* Post::Part::GetFeature(int i) const
References _featureList.
Referenced by GetFeatureByName, GetInfo, ToCATIA.
Feature * Post::Part::GetFeatureByName(string name)
References GetFeature, Post::Feature::GetFeatureName, GetSize.
Referenced by Post::FeatureSOLIDCreateCutExtrude::GetInfo, Post::FeatureSOLIDCreateCutRevolve::GetInfo, Post::FeatureSOLIDCreateProtrusionRevolve::GetInfo, Post::FeatureSOLIDCreateProtrusionExtrude::GetInfo, Post::FeatureSOLIDCreateProtrusionSweep::GetInfo, Post::FSketch::ToCATIA.
size_t Post::Part::GetSize() const
References _featureList.
Referenced by Post::Feature::Feature, GetFeatureByName, GetInfo, ToCATIA.
void Post::Part::GetInfo()
References _spFeatures, CreateFeature, GetFeature, GetSize.
Referenced by ReferenceClass::ref_Post::AssemblyPartT2C, Post::CATIAPostTranslate, ReferenceClass::ref_Post::T2C_ReferenceName_From_Part.
void Post::Part::ToCATIA()
References GetFeature, GetSize.
Referenced by ReferenceClass::ref_Post::AssemblyPartT2C, Post::CATIAPostTranslate.
void Post::Part::ExternModeToggle(int mode)
References ExternMode.
Referenced by ReferenceClass::ref_Post::AssemblyPartT2C, ReferenceClass::ref_Post::T2C_ReferenceName_From_Part.
void Post::Part::InitReferManager()
References ang_index, arr_index, circle_index, DatumPlaneID, fac_index, holecounterID, lim_index, ln_index, lng_index, pt_index, ref_index, repname_index, sktch.
Referenced by ReferenceClass::ref_Post::AssemblyPartT2C, ReferenceClass::ref_Post::T2C_ReferenceName_From_Part.
Feature * Post::Part::CreateFeature(TransCAD::IFeaturePtr spFeature)
References _featureList, Post::CATIAReferenceManager::AddNewFeature, Post::g_pRefManager.
Referenced by GetInfo.