Post::SKETCHItem
FSketch* Post::SKETCHItem::_pFSketch
Referenced by GetFeatureSketch, Post::SKETCHCreate2DCenterline::GetInfo, Post::SKETCHCreate2DPoint::GetInfo, Post::SKETCHCreate2DCircleCenterPoint::GetInfo, Post::SKETCHCreate2DLine2Points::GetInfo, Post::SKETCHCreate2DCircularArc::GetInfo, SKETCHItem, Post::SKETCHCreate2DCenterline::ToCATIA, Post::SKETCHCreate2DPoint::ToCATIA, Post::SKETCHCreate2DCircleCenterPoint::ToCATIA, Post::SKETCHCreate2DLine2Points::ToCATIA, Post::SKETCHCreate2DCircularArc::ToCATIA.
string Post::SKETCHItem::_strName
Referenced by GetSketchItemName, SKETCHItem.
TransCAD::IStdSketchGeometryPtr Post::SKETCHItem::_spItem
Referenced by GetTransCADGeometryItem, GetType, SKETCHItem.
size_t Post::SKETCHItem::_nIndex
Referenced by SKETCHItem.
Post::SKETCHItem::SKETCHItem(FSketch *pFSketch, TransCAD::IStdSketchGeometryPtr spItem)
References _nIndex, _pFSketch, _spItem, _strName, Post::FSketch::GetSketchItemsSize.
Post::SKETCHItem::~SKETCHItem(void)
FSketch* Post::SKETCHItem::GetFeatureSketch()
References _pFSketch.
Referenced by Post::SKETCHCreate2DCenterline::ToCATIA, Post::SKETCHCreate2DPoint::ToCATIA, Post::SKETCHCreate2DLine2Points::ToCATIA, Post::SKETCHCreate2DCircleCenterPoint::ToCATIA, Post::SKETCHCreate2DCircularArc::ToCATIA.
string Post::SKETCHItem::GetSketchItemName()
References _strName.
Referenced by Post::SKETCHCreate2DCenterline::ToCATIA, Post::SKETCHCreate2DLine2Points::ToCATIA, Post::SKETCHCreate2DCircleCenterPoint::ToCATIA, Post::SKETCHCreate2DCircularArc::ToCATIA.
TransCAD::IStdSketchGeometryPtr Post::SKETCHItem::GetTransCADGeometryItem()
References _spItem.
Referenced by Post::SKETCHCreate2DCenterline::GetInfo, Post::SKETCHCreate2DPoint::GetInfo, Post::SKETCHCreate2DLine2Points::GetInfo, Post::SKETCHCreate2DCircleCenterPoint::GetInfo, Post::SKETCHCreate2DCircularArc::GetInfo.
TransCAD::StdSketchGeometryType Post::SKETCHItem::GetType()
References _spItem.
void Post::SKETCHItem::GetInfo()
Referenced by Post::FSketch::GetInfo, Post::FSketch::ToCATIA.
void Post::SKETCHItem::ToCATIA()
Referenced by Post::FSketch::ToCATIA.