Pre::FSketch
ReferenceEntity* Pre::FSketch::_pReferenceEntity
Referenced by GetInfo, GetReferenceEntity.
std::vector<FSKETCHItem*> Pre::FSketch::_sketchItemList
Referenced by Clear, CreateSketchItem, GetSketchItem, GetSketchItemFromName, GetSketchItemsSize.
vector<ReportItem> Pre::FSketch::reportNameTable
Referenced by AddEntityNameReportName, GetEntityNameFromReportName.
double Pre::FSketch::sketchCoord[9][9]
Referenced by Pre::FeatureSOLIDCreatePatternCircular::CreateAxis, Pre::FeatureSOLIDCreateRevolve::CreateRevolveAxis, GetInfo, ToTransCAD.
int Pre::FSketch::id
int Pre::FSketch::type
Referenced by GetInfo, GetSketchItemInfo.
string Pre::FSketch::_factoryName
Referenced by CreateSketchItem, GetFactoryName.
string Pre::FSketch::_axisName
Referenced by CreateSketchItem, GetAxisName.
TransCAD::ISketchEditorPtr Pre::FSketch::_spSketEditor
Referenced by GetSketchEditorPtr, ToTransCAD, ~FSketch.
TransCAD::IStdSketchFeaturePtr Pre::FSketch::_spSketch
Referenced by GetSketchFeaturePtr, ToTransCAD, ~FSketch.
Pre::FSketch::FSketch(Part *pPart, int type, string name)
Pre::FSketch::~FSketch(void)
References _spSketch, _spSketEditor, Clear.
void Pre::FSketch::Clear()
References _sketchItemList.
Referenced by ~FSketch.
FSKETCHItem* Pre::FSketch::GetSketchItem(int index) const
References _sketchItemList.
Referenced by ToTransCAD.
size_t Pre::FSketch::GetSketchItemsSize() const
References _sketchItemList.
Referenced by ToTransCAD.
string Pre::FSketch::GetFactoryName()
References _factoryName.
Referenced by Pre::FSKETCHCreate2DCircleCenterPoint::GetInfo.
string Pre::FSketch::GetAxisName()
References _axisName.
virtual ReferenceEntity* Pre::FSketch::GetReferenceEntity()
References _pReferenceEntity.
Referenced by ToTransCAD.
FSKETCHItem * Pre::FSketch::GetSketchItemFromName(string name)
References _sketchItemList.
Referenced by Pre::FeatureSOLIDCreateRevolve::AddNewRevolveAxis, GetSketchItemInfo, Pre::FeatureSOLIDCreatePatternCircular::SetDirection.
void Pre::FSketch::AddEntityNameReportName(int reportName, string entityName)
References Pre::ReportItem::_entityName, Pre::ReportItem::_reportName, reportNameTable.
Referenced by Pre::FSKETCHCreate2DPoint::Modify, Pre::FSKETCHCreate2DLine2Points::Modify, Pre::FSKETCHCreate2DCircleCenterPoint::Modify.
string Pre::FSketch::GetEntityNameFromReportName(int reportName)
References reportNameTable.
virtual TransCAD::ISketchEditorPtr Pre::FSketch::GetSketchEditorPtr()
References _spSketEditor.
Referenced by Pre::FSKETCHCreate2DLine2Points::ToTransCAD, Pre::FSKETCHCreate2DCircleCenterPoint::ToTransCAD.
virtual TransCAD::IStdSketchFeaturePtr Pre::FSketch::GetSketchFeaturePtr()
References _spSketch.
Referenced by Pre::FeatureSOLIDCreateRevolve::CreateRevolveAxis.
void Pre::FSketch::GetInfo(ifstream &is)
References Pre::Feature::_pPart, _pReferenceEntity, Pre::Part::GetReferenceEntityByName, GetSketchItemInfo, sketchCoord, type.
void Pre::FSketch::GetSketchItemInfo(ifstream &is)
References Pre::Feature::_name, CreateSketchItem, GetSketchItemFromName, Pre::FSKETCHItem::Modify, Pre::FSKETCHItem::SetCenterLineInfo, type.
Referenced by GetInfo, Pre::Part::GetInfo.
void Pre::FSketch::ToTransCAD()
References Pre::Part::_spFeatures, _spSketch, _spSketEditor, Pre::Feature::GetFeatureName, Pre::Feature::GetPart, GetReferenceEntity, GetSketchItem, GetSketchItemsSize, sketchCoord, Pre::ReferenceEntity::ToTransCAD, Pre::FSKETCHItem::ToTransCAD.
void Pre::FSketch::Modify(char *buffer)
void Pre::FSketch::CreateSketchItem(string type, string name, ifstream &is)
References _axisName, _factoryName, _sketchItemList, Pre::FSKETCHItem::GetInfo.
Referenced by GetSketchItemInfo.