CATIATranslator::Part
INFITF.Application CATIATranslator.Part.cApp
Referenced by CATIATranslator.Part.InitializeCATIA.
INFITF.Documents CATIATranslator.Part.cDocs
Referenced by CATIATranslator.Part.InitializeCATIA.
MECMOD.PartDocument CATIATranslator.Part.cPartDoc
Referenced by CATIATranslator.Part.InitializeCATIA.
MECMOD.Part CATIATranslator.Part.cPart
Referenced by CATIATranslator.Part.InitializeCATIA, CATIATranslator.Part.UninitializeCATIA.
MECMOD.OriginElements CATIATranslator.Part.cOriginalElements
Referenced by CATIATranslator.Reference.GetCATIASketchReference, CATIATranslator.FeatureRectPattern.GetReferencePlane, CATIATranslator.FeatureCircPattern.GetRotationAxis, CATIATranslator.Part.InitializeCATIA, CATIATranslator.Part.UninitializeCATIA.
MECMOD.Bodies CATIATranslator.Part.cBodies
Referenced by CATIATranslator.Part.InitializeCATIA, CATIATranslator.Part.UninitializeCATIA.
MECMOD.Body CATIATranslator.Part.cCurrentBody
Referenced by CATIATranslator.Part.InitializeCATIA, CATIATranslator.Part.UninitializeCATIA.
MECMOD.Shapes CATIATranslator.Part.cShapes
Referenced by CATIATranslator.Part.InitializeCATIA, CATIATranslator.FeatureCircPattern.TranslateT2C, CATIATranslator.FeatureRectPattern.TranslateT2C, CATIATranslator.Part.UninitializeCATIA.
MECMOD.Factory CATIATranslator.Part.cFactory
Referenced by CATIATranslator.Part.InitializeCATIA, CATIATranslator.Part.UninitializeCATIA.
MECMOD.Sketches CATIATranslator.Part.cSketches
Referenced by CATIATranslator.Part.InitializeCATIA, CATIATranslator.Part.UninitializeCATIA.
PARTITF.ShapeFactory CATIATranslator.Part.cShapeFactory
Referenced by CATIATranslator.Part.InitializeCATIA, CATIATranslator.Part.UninitializeCATIA.
HybridShapeTypeLib.HybridShapeFactory CATIATranslator.Part.cHybridShapeFactory
Referenced by CATIATranslator.Part.InitializeCATIA, CATIATranslator.Part.UninitializeCATIA.
TransCAD.Application CATIATranslator.Part.tApp
Referenced by CATIATranslator.Part.InitializeTransCAD, CATIATranslator.Part.UninitializeTransCAD.
TransCAD.Documents CATIATranslator.Part.tDocs
Referenced by CATIATranslator.Part.InitializeTransCAD, CATIATranslator.Part.UninitializeTransCAD.
TransCAD.IAssemDocument CATIATranslator.Part.tAssemDoc
Referenced by CATIATranslator.Part.InitializeTransCAD, CATIATranslator.Part.UninitializeTransCAD.
TransCAD.Assem CATIATranslator.Part.tAssem
TransCAD.IComp CATIATranslator.Part.tComp
TransCAD.PartDocument CATIATranslator.Part.tPartDoc
Referenced by CATIATranslator.Part.InitializeTransCAD, CATIATranslator.Part.UninitializeTransCAD.
TransCAD.Part CATIATranslator.Part.tPart
Referenced by CATIATranslator.Part.InitializeTransCAD, CATIATranslator.Part.UninitializeTransCAD.
TransCAD.Features CATIATranslator.Part.tFeatures
Referenced by CATIATranslator.Part.InitializeTransCAD, CATIATranslator.Part.UninitializeTransCAD.
Reference CATIATranslator.Part.ReferenceManager
Referenced by CATIATranslator.Part.InitializeCATIA, CATIATranslator.Part.InitializeTransCAD, CATIATranslator.FeatureChamfer.TranslateT2C, CATIATranslator.FeatureEdgeFillet.TranslateT2C, CATIATranslator.FeatureCircPattern.TranslateT2C, CATIATranslator.FeatureRectPattern.TranslateT2C.
bool CATIATranslator.Part.isSubAssemblyPart
Referenced by CATIATranslator.Part.InitializeTransCAD.
int CATIATranslator.Part.partNum
bool CATIATranslator.Part.InitializeCATIA(string filePath, int mode)
References CATIATranslator.Part.cApp, CATIATranslator.Part.cBodies, CATIATranslator.Part.cCurrentBody, CATIATranslator.Part.cDocs, CATIATranslator.Part.cFactory, CATIATranslator.Part.cHybridShapeFactory, CATIATranslator.Part.cOriginalElements, CATIATranslator.Part.cPart, CATIATranslator.Part.cPartDoc, CATIATranslator.Part.cShapeFactory, CATIATranslator.Part.cShapes, CATIATranslator.Part.cSketches, CATIATranslator.Part.ReferenceManager.
Referenced by CATIATranslator.Form1.button1_Click, CATIATranslator.Program.Main.
void CATIATranslator.Part.UninitializeCATIA()
References CATIATranslator.Part.cBodies, CATIATranslator.Part.cCurrentBody, CATIATranslator.Part.cFactory, CATIATranslator.Part.cHybridShapeFactory, CATIATranslator.Part.cOriginalElements, CATIATranslator.Part.cPart, CATIATranslator.Part.cShapeFactory, CATIATranslator.Part.cShapes, CATIATranslator.Part.cSketches.
void CATIATranslator.Part.TranslateC2T()
void CATIATranslator.Part.SaveCATPartFile(string filePath)
INFITF.AnyObject CATIATranslator.Part.GetRecentFeature()
bool CATIATranslator.Part.InitializeTransCAD(int mode)
References CATIATranslator.Part.isSubAssemblyPart, CATIATranslator.Part.ReferenceManager, CATIATranslator.Part.tApp, CATIATranslator.Part.tAssemDoc, CATIATranslator.Part.tDocs, CATIATranslator.Part.tFeatures, CATIATranslator.Part.tPart, CATIATranslator.Part.tPartDoc.
Referenced by CATIATranslator.Form1.button2_Click, CATIATranslator.Program.Main.
void CATIATranslator.Part.UninitializeTransCAD()
References CATIATranslator.Part.tApp, CATIATranslator.Part.tAssemDoc, CATIATranslator.Part.tDocs, CATIATranslator.Part.tFeatures, CATIATranslator.Part.tPart, CATIATranslator.Part.tPartDoc.
void CATIATranslator.Part.TranslateT2C()
void CATIATranslator.Part.TranslateT2C(TransCAD.IPart tPart)
TransCAD.IFeature CATIATranslator.Part.GetFeatureFromReference(TransCAD.Reference reference)