Pre::FeatureSOLIDCreateRevolve
double Pre::FeatureSOLIDCreateRevolve::startAngle
Referenced by CheckAttribute, FeatureSOLIDCreateRevolve, ToTransCAD.
double Pre::FeatureSOLIDCreateRevolve::endAngle
Referenced by CheckAttribute, FeatureSOLIDCreateRevolve, ToTransCAD.
string Pre::FeatureSOLIDCreateRevolve::startCondition
Referenced by FeatureSOLIDCreateRevolve.
string Pre::FeatureSOLIDCreateRevolve::endCondition
Referenced by FeatureSOLIDCreateRevolve.
string Pre::FeatureSOLIDCreateRevolve::_revolveAxis
Referenced by AddNewRevolveAxis, Modify.
Point3D Pre::FeatureSOLIDCreateRevolve::origin
Referenced by AddNewRevolveAxis, GetAxisOrigin.
Point3D Pre::FeatureSOLIDCreateRevolve::direction
Referenced by AddNewRevolveAxis, GetAxisDirection.
int Pre::FeatureSOLIDCreateRevolve::flip
Referenced by FeatureSOLIDCreateRevolve.
FSketch* Pre::FeatureSOLIDCreateRevolve::_featureProfileSketch
Referenced by FeatureSOLIDCreateRevolve, GetFeatureProfileSketch, GetInfo, ToTransCAD.
vector<ReferenceEntity *> Pre::FeatureSOLIDCreateRevolve::_referenceEntityList
Referenced by GetInfo, Modify, ToTransCAD.
Pre::FeatureSOLIDCreateRevolve::FeatureSOLIDCreateRevolve(Part *pPart, int type, string name)
References _featureProfileSketch, endAngle, endCondition, flip, startAngle, startCondition.
Pre::FeatureSOLIDCreateRevolve::~FeatureSOLIDCreateRevolve()
FSketch* Pre::FeatureSOLIDCreateRevolve::GetFeatureProfileSketch()
References _featureProfileSketch.
Referenced by ToTransCAD.
void Pre::FeatureSOLIDCreateRevolve::GetInfo(ifstream &is)
References _featureProfileSketch, Pre::Feature::_pPart, _referenceEntityList, Pre::Part::AddFeatureNameSketchName, Pre::Part::GetFeatureByName, Pre::Feature::GetFeatureName, Pre::ReferenceEntity::GetFeatureName, Pre::Feature::GetPart, Pre::Part::GetReferenceEntityByName.
void Pre::FeatureSOLIDCreateRevolve::ToTransCAD()
References _featureProfileSketch, Pre::Feature::_name, _referenceEntityList, Pre::Part::_spFeatures, Pre::Part::_spPart, Pre::Feature::_type, AddNewRevolveAxis, endAngle, Pre::Feature::GetFeatureName, GetFeatureProfileSketch, Pre::Feature::GetPart, startAngle.
void Pre::FeatureSOLIDCreateRevolve::CheckAttribute(string name, double value, int type)
References endAngle, startAngle.
void Pre::FeatureSOLIDCreateRevolve::Modify(char *buffer)
References Pre::Feature::_pPart, _referenceEntityList, _revolveAxis, Pre::Part::AddFeatureNameSketchName, Pre::Feature::GetFeatureName, Pre::ReferenceEntity::GetFeatureName, Pre::Feature::GetPart, Pre::Part::GetReferenceEntityByName.
Point3D Pre::FeatureSOLIDCreateRevolve::GetAxisOrigin()
References origin.
Referenced by AddNewRevolveAxis.
Point3D Pre::FeatureSOLIDCreateRevolve::GetAxisDirection()
References direction.
Referenced by AddNewRevolveAxis.
void Pre::FeatureSOLIDCreateRevolve::AddNewRevolveAxis()
References Pre::Feature::_name, _revolveAxis, WireInfo::_sketchItemName, WireInfo::_sketchName, CreateRevolveAxis, direction, GetAxisDirection, GetAxisOrigin, Pre::FSKETCHCreate2DCircleCenterPoint::GetCenterPoint, Pre::FSKETCHCreate2DLine2Points::GetEndPoint, Pre::Part::GetFeatureByName, Pre::Part::GetFeatureNameFromSketchName, Pre::Feature::GetPart, Pre::Part::GetReferenceEntityByName, Pre::FSketch::GetSketchItemFromName, Pre::Part::GetSketchNameFromFeatureName, Pre::FSKETCHCreate2DLine2Points::GetStartPoint, Pre::ReferenceEntity::GetWireInfo, origin.
Referenced by ToTransCAD.
void Pre::FeatureSOLIDCreateRevolve::CreateRevolveAxis(FSketch *pRefSketch, FSketch *pRevSketch, Point3D origin, Point3D direction)
References Pre::FSketch::GetSketchFeaturePtr, Pre::FSketch::sketchCoord, TransformRevolveAxis.
Referenced by AddNewRevolveAxis.
void Pre::FeatureSOLIDCreateRevolve::TransformRevolveAxis(double refSketCSYS[9], double revSketCSYS[9], Point3D &coords)
References TransformCoordinates.
Referenced by CreateRevolveAxis.
void Pre::FeatureSOLIDCreateRevolve::TransformCoordinates(double sourceCSYS[3][3], double targetCSYS[3][3], Point3D &coords)
Referenced by TransformRevolveAxis.