Pre::Vector3D
double Pre::Vector3D::_x
Referenced by Norm, operator*, operator+, operator-, operator/, operator=, operator==, operator[], operator^, SetX, SetXYZ, Size, X.
double Pre::Vector3D::_y
Referenced by Norm, operator*, operator+, operator-, operator/, operator=, operator==, operator^, SetXYZ, SetY, Size, Y.
double Pre::Vector3D::_z
Referenced by Norm, operator*, operator+, operator-, operator/, operator=, operator==, operator^, SetXYZ, SetZ, Size, Z.
Pre::Vector3D::Vector3D(void)
Referenced by Norm, operator*, operator+, operator-, operator/, operator^.
Pre::Vector3D::Vector3D(double x, double y, double z)
Pre::Vector3D::Vector3D(double coord[])
double Pre::Vector3D::X(void) const
References _x.
double Pre::Vector3D::Y(void) const
References _y.
double Pre::Vector3D::Z(void) const
References _z.
void Pre::Vector3D::SetX(double x)
References _x.
void Pre::Vector3D::SetY(double y)
References _y.
void Pre::Vector3D::SetZ(double z)
References _z.
void Pre::Vector3D::SetXYZ(double sz[3])
References _x, _y, _z.
void Pre::Vector3D::SetXYZ(double x, double y, double z)
References _x, _y, _z.
double& Pre::Vector3D::operator[](int i)
References _x.
Vector3D Pre::Vector3D::operator+(const Vector3D &rhs)
References _x, _y, _z, Vector3D.
Vector3D Pre::Vector3D::operator-(const Vector3D &rhs)
References _x, _y, _z, Vector3D.
Vector3D Pre::Vector3D::operator*(double d)
References _x, _y, _z, Vector3D.
Vector3D Pre::Vector3D::operator/(double d)
References _x, _y, _z, Vector3D.
double Pre::Vector3D::operator*(Vector3D &d)
References _x, _y, _z.
Vector3D Pre::Vector3D::operator^(Vector3D &d)
References _x, _y, _z, Vector3D.
bool Pre::Vector3D::operator==(const Vector3D &rhs)
References _x, _y, _z.
void Pre::Vector3D::operator=(const Vector3D &rhs)
References _x, _y, _z.
double Pre::Vector3D::Size() const
References _x, _y, _z.
Referenced by Norm.
Vector3D Pre::Vector3D::Norm(void)
References _x, _y, _z, Size, Vector3D.