Pre::Part
ifstream Pre::Part::fin
Referenced by GetInfo, ~Part.
TransCAD::IDocsPtr Pre::Part::_spDocuments
Referenced by ~Part.
TransCAD::IPartDocumentPtr Pre::Part::_spDocument
Referenced by ~Part.
TransCAD::IPartPtr Pre::Part::_spPart
Referenced by ReferenceClass::ref_Pre::TestEnvironment, Pre::FeatureSOLIDCreateSweep::ToTransCAD, Pre::FeatureSOLIDCreatePatternRectangular::ToTransCAD, Pre::FeatureSOLIDCreatePatternCircular::ToTransCAD, Pre::FeatureSOLIDCreateChamfer::ToTransCAD, Pre::FeatureSOLIDCreateRevolve::ToTransCAD, Pre::FeatureSOLIDCreateFilletConstant::ToTransCAD, Pre::FeatureSOLIDCreateExtrude::ToTransCAD, Pre::ReferenceEntity::ToTransCAD, ~Part.
TransCAD::IFeaturesPtr Pre::Part::_spFeatures
Referenced by Pre::FeatureSOLIDCreateSweep::ToTransCAD, Pre::FDatumPlaneOffset::ToTransCAD, Pre::FeatureSOLIDCreateHole::ToTransCAD, Pre::FeatureSOLIDCreatePatternRectangular::ToTransCAD, Pre::FeatureSOLIDCreatePatternCircular::ToTransCAD, Pre::FeatureSOLIDCreateChamfer::ToTransCAD, Pre::FeatureSOLIDCreateRevolve::ToTransCAD, Pre::FeatureSOLIDCreateFilletConstant::ToTransCAD, Pre::FeatureSOLIDCreateExtrude::ToTransCAD, Pre::FSketch::ToTransCAD, ~Part.
int Pre::Part::_partDocNum
Referenced by GetPartDocNumber.
vector<Feature*> Pre::Part::_featureList
Referenced by Clear, CreateFeature, GetFeature, GetSize.
vector<AttributeItem*> Pre::Part::_attributeItemList
Referenced by Clear, CreateAttributeItem, GetAttributeItem, GetAttributeItemByName.
vector<ReferenceEntity*> Pre::Part::_referenceEntityList
Referenced by Clear, CreateReferenceEntity, GetReferenceEntity, GetReferenceEntityByName.
vector<SketchFeature> Pre::Part::sketchNameTable
Referenced by AddFeatureNameSketchName, GetFeatureNameFromSketchName, GetSketchNameFromFeatureName.
string Pre::Part::_filePath
string Pre::Part::_fileName
Pre::Part::Part(string fileName)
References Post::Part::_spDocument, Post::Part::_spFeatures, Post::Part::_spPart, Post::Part::_strPartName, Post::Part::file.
Pre::Part::Part::Part(string fileName, int partNum)
Pre::Part::Part::Part(string fileName, TransCAD::IPartDocumentPtr partdoc)
Pre::Part::~Part(void)
References _planeDatumNumber, _spDocument, _spDocuments, _spFeatures, _spPart, Clear, fin, Pre::g_spApplication.
void Pre::Part::Clear()
References _attributeItemList, _featureList, _referenceEntityList.
Referenced by ~Part.
Feature* Pre::Part::GetFeature(int i) const
References _featureList.
Referenced by GetFeatureByName, ToTransCAD.
Feature * Pre::Part::GetFeatureByName(string name)
References GetFeature, Pre::Feature::GetFeatureName, GetSize.
Referenced by Pre::FeatureSOLIDCreateRevolve::AddNewRevolveAxis, Pre::AttLinearRepartation::CheckAttribute, Pre::AttAngularRepartation::CheckAttribute, Pre::AttLimit::CheckAttribute, Pre::ReferenceEntity::GetBasicFaceName, Pre::FeatureSOLIDCreateRevolve::GetInfo, Pre::FeatureSOLIDCreateExtrude::GetInfo, Pre::ReferenceEntity::GetInfo, GetInfo, Pre::ReferenceEntity::GetReferName, Pre::AttLimit::Modify, Pre::AttLength::Modify, Pre::AttParameter::Modify, Pre::AttAngle::Modify, Pre::FeatureSOLIDCreatePatternCircular::SetDirection.
ReferenceEntity* Pre::Part::GetReferenceEntity(int i) const
References _referenceEntityList.
Referenced by GetReferenceEntityByName.
ReferenceEntity * Pre::Part::GetReferenceEntityByName(string name)
References _referenceEntityList, Pre::ReferenceEntity::GetName, GetReferenceEntity.
Referenced by Pre::FeatureSOLIDCreateRevolve::AddNewRevolveAxis, Pre::FeatureSOLIDCreateSweep::GetInfo, Pre::FDatumPlaneOffset::GetInfo, Pre::FeatureSOLIDCreateHole::GetInfo, Pre::FeatureSOLIDCreateChamfer::GetInfo, Pre::FeatureSOLIDCreateFilletConstant::GetInfo, Pre::FeatureSOLIDCreateRevolve::GetInfo, Pre::FeatureSOLIDCreateExtrude::GetInfo, Pre::FSketch::GetInfo, Pre::FeatureSOLIDCreateSweep::Modify, Pre::FeatureSOLIDCreatePatternRectangular::Modify, Pre::FeatureSOLIDCreatePatternCircular::Modify, Pre::FeatureSOLIDCreateChamfer::Modify, Pre::FeatureSOLIDCreateFilletConstant::Modify, Pre::FeatureSOLIDCreateRevolve::Modify, Pre::FeatureSOLIDCreateExtrude::Modify, Pre::FeatureSOLIDCreatePatternRectangular::SetDirection, Pre::FeatureSOLIDCreatePatternCircular::SetDirection.
AttributeItem* Pre::Part::GetAttributeItem(int i) const
References _attributeItemList.
Referenced by GetAttributeItemByName.
AttributeItem * Pre::Part::GetAttributeItemByName(string name)
References _attributeItemList, GetAttributeItem, Pre::AttributeItem::GetName.
Referenced by GetInfo, Pre::AttParameter::Modify, Pre::AttLength::Modify, Pre::AttIntParam::Modify, Pre::AttAngle::Modify.
void Pre::Part::AddFeatureNameSketchName(string featureName, string sketchName)
References Pre::SketchFeature::_featureName, Pre::SketchFeature::_sketchName, sketchNameTable.
Referenced by Pre::FeatureSOLIDCreateSweep::GetInfo, Pre::FeatureSOLIDCreateRevolve::GetInfo, Pre::FeatureSOLIDCreateExtrude::GetInfo, Pre::FeatureSOLIDCreateSweep::Modify, Pre::FeatureSOLIDCreateRevolve::Modify, Pre::FeatureSOLIDCreateExtrude::Modify.
string Pre::Part::GetSketchNameFromFeatureName(string featureName)
References sketchNameTable.
Referenced by Pre::FeatureSOLIDCreateRevolve::AddNewRevolveAxis.
string Pre::Part::GetFeatureNameFromSketchName(string sketchName)
References sketchNameTable.
Referenced by Pre::FeatureSOLIDCreateRevolve::AddNewRevolveAxis.
size_t Pre::Part::GetSize() const
References _featureList.
Referenced by GetFeatureByName, ToTransCAD.
void Pre::Part::GetInfo()
References CreateAttributeItem, CreateFeature, CreateReferenceEntity, fin, GetAttributeItemByName, GetFeatureByName, Pre::FSketch::GetSketchItemInfo, Pre::AttributeItem::Modify, Pre::Feature::Modify.
Referenced by Pre::CATIAPreTranslate, ReferenceClass::ref_Pre::GetTransCADName_from_buffer, ReferenceClass::ref_Pre::TestEnvironment.
void Pre::Part::ToTransCAD()
References GetFeature, GetSize, Pre::Feature::ToTransCAD.
Referenced by Pre::CATIAPreTranslate, ReferenceClass::ref_Pre::TestEnvironment.
int Pre::Part::GetPartDocNumber()
References _partDocNum.
Referenced by Pre::CATIAPreTranslate.
void Pre::Part::CreateFeature(string type, string name, ifstream &is)
References _featureList, _planeDatumNumber, Pre::Feature::GetInfo.
Referenced by GetInfo.
void Pre::Part::CreateAttributeItem(string type, string name, ifstream &is)
References _attributeItemList, Pre::AttributeItem::GetInfo.
Referenced by GetInfo.
void Pre::Part::CreateReferenceEntity(string type, string name, ifstream &is)
References _referenceEntityList, Pre::ReferenceEntity::GetInfo.
Referenced by GetInfo.