Pre::FeatureSOLIDCreateHole
string Pre::FeatureSOLIDCreateHole::_selected_face
string Pre::FeatureSOLIDCreateHole::_center
double Pre::FeatureSOLIDCreateHole::center[3][3]
Referenced by GetInfo, ToTransCAD.
double Pre::FeatureSOLIDCreateHole::radius
Referenced by CheckAttribute, GetInfo, ModifyCounterbore, ModifyCountersunk, ToTransCAD.
double Pre::FeatureSOLIDCreateHole::depth
Referenced by GetInfo, ModifyCounterbore, ToTransCAD.
int Pre::FeatureSOLIDCreateHole::end_condition
Referenced by FeatureSOLIDCreateHole.
bool Pre::FeatureSOLIDCreateHole::flip
Referenced by FeatureSOLIDCreateHole.
double Pre::FeatureSOLIDCreateHole::lower_hole_diameter
Referenced by ModifyCounterbore, ToTransCAD.
double Pre::FeatureSOLIDCreateHole::lower_hole_depth
Referenced by ModifyCounterbore.
double Pre::FeatureSOLIDCreateHole::bottom_angle
Referenced by CheckAttribute, FeatureSOLIDCreateHole, ToTransCAD.
double Pre::FeatureSOLIDCreateHole::head_diameter
Referenced by CheckAttribute, ModifyCounterbore, ToTransCAD.
double Pre::FeatureSOLIDCreateHole::head_angle
Referenced by CheckAttribute, ModifyCountersunk, ToTransCAD.
double Pre::FeatureSOLIDCreateHole::head_depth
Referenced by CheckAttribute, ModifyCountersunk, ToTransCAD.
double Pre::FeatureSOLIDCreateHole::upper_hole_diameter
Referenced by ModifyCounterbore.
double Pre::FeatureSOLIDCreateHole::upper_hole_depth
Referenced by ModifyCounterbore.
double Pre::FeatureSOLIDCreateHole::countersink_angle
Referenced by ModifyCountersunk.
double Pre::FeatureSOLIDCreateHole::countersink_radius
Referenced by ModifyCountersunk, ToTransCAD.
int Pre::FeatureSOLIDCreateHole::hole_type
Referenced by CheckAttribute, FeatureSOLIDCreateHole, Modify, ToTransCAD.
double Pre::FeatureSOLIDCreateHole::bottom_limit_dim
Referenced by ModifyCounterbore.
bool Pre::FeatureSOLIDCreateHole::depth_default
Referenced by FeatureSOLIDCreateHole.
vector<ReferenceEntity *> Pre::FeatureSOLIDCreateHole::_referenceEntityList
Referenced by GetInfo, ToTransCAD.
Pre::FeatureSOLIDCreateHole::FeatureSOLIDCreateHole(Part *pPart, int type, string name)
References bottom_angle, depth_default, end_condition, flip, hole_type.
Pre::FeatureSOLIDCreateHole::~FeatureSOLIDCreateHole()
void Pre::FeatureSOLIDCreateHole::GetInfo(ifstream &is)
References Pre::Feature::_pPart, _referenceEntityList, center, depth, Pre::Part::GetReferenceEntityByName, radius.
void Pre::FeatureSOLIDCreateHole::ToTransCAD()
References Pre::Feature::_name, _referenceEntityList, Pre::Part::_spFeatures, bottom_angle, center, countersink_radius, depth, Pre::Feature::GetPart, head_angle, head_depth, head_diameter, hole_type, lower_hole_diameter, radius.
void Pre::FeatureSOLIDCreateHole::Modify(char *buffer)
References hole_type, ModifyCounterbore, ModifyCountersunk.
void Pre::FeatureSOLIDCreateHole::CheckAttribute(string name, double value, int type)
References bottom_angle, head_angle, head_depth, head_diameter, hole_type, ModifyCounterbore, ModifyCountersunk, radius.
void Pre::FeatureSOLIDCreateHole::ModifyCounterbore()
References bottom_limit_dim, depth, head_diameter, lower_hole_depth, lower_hole_diameter, radius, upper_hole_depth, upper_hole_diameter.
Referenced by CheckAttribute, Modify.
void Pre::FeatureSOLIDCreateHole::ModifyCountersunk()
References countersink_angle, countersink_radius, head_angle, head_depth, PI, radius.
Referenced by CheckAttribute, Modify.