CATIATranslator::Reference
Part CATIATranslator.Reference.PartManager
Referenced by CATIATranslator.Reference.GetCATIASketchReference, CATIATranslator.Reference.Reference.
Dictionary<string, string> CATIATranslator.Reference.NameMap
Referenced by CATIATranslator.Reference.GetCATIABasicName, CATIATranslator.Reference.GetCATIANameFromTransCADName, CATIATranslator.FeatureCircPattern.TranslateT2C, CATIATranslator.FeatureRectPattern.TranslateT2C.
Assembly CATIATranslator.Reference.assembly
Referenced by CATIATranslator.Reference.Reference.
CATIATranslator.Reference.Reference(Part PartManager)
References CATIATranslator.Reference.PartManager.
CATIATranslator.Reference.Reference(Assembly assembly)
References CATIATranslator.Reference.assembly.
string CATIATranslator.Reference.GetTransCADNameFromCATIAName(string cName)
References CATIATranslator.Reference.GetTransCADBasicName.
string CATIATranslator.Reference.GetTransCADBasicName(string[] cName)
References CATIATranslator.Reference.GetSketchElementNameByReportName, CATIATranslator.Reference.GetTransCADFeatureType.
Referenced by CATIATranslator.Reference.GetTransCADNameFromCATIAName.
string CATIATranslator.Reference.GetSketchElementNameByReportName(string cSketchName, string cReportName)
Referenced by CATIATranslator.Reference.GetTransCADBasicName.
string CATIATranslator.Reference.GetTransCADFeatureType(string cFeatureName)
Referenced by CATIATranslator.Reference.GetTransCADBasicName.
TransCAD.Reference CATIATranslator.Reference.GetTransCADSketchReference(MECMOD.Sketch cSketch)
References CATIATranslator.Reference.GetTransCADPlaneType.
int CATIATranslator.Reference.GetTransCADPlaneType(object[] axis)
Referenced by CATIATranslator.Reference.GetTransCADSketchReference.
string CATIATranslator.Reference.GetCATIANameFromTransCADName(string tName)
References CATIATranslator.Reference.GetCATIABasicName, CATIATranslator.Reference.NameMap.
Referenced by CATIATranslator.FeatureChamfer.TranslateT2C, CATIATranslator.FeatureEdgeFillet.TranslateT2C.
string CATIATranslator.Reference.GetCATIANameFromTransCADNameForHole(string tName)
References CATIATranslator.Reference.GetCATIABasicName.
string CATIATranslator.Reference.GetCATIABasicName(string[] tName)
References CATIATranslator.Reference.GetReportNameBySketchElementName, CATIATranslator.Reference.NameMap.
Referenced by CATIATranslator.Reference.GetCATIANameFromTransCADName, CATIATranslator.Reference.GetCATIANameFromTransCADNameForHole.
string CATIATranslator.Reference.GetReportNameBySketchElementName(string tSketchName, string tSketchElementName)
Referenced by CATIATranslator.Reference.GetCATIABasicName.
INFITF.Reference CATIATranslator.Reference.GetCATIASketchReference(TransCAD.IStdSketchFeature tSketch)
References CATIATranslator.Part.cOriginalElements, CATIATranslator.Reference.PartManager.