Pre::FSKETCHCreate2DCircleCenterPoint
double Pre::FSKETCHCreate2DCircleCenterPoint::center[3][3]
Referenced by ConvertRadToDeg, GetCenterPoint, GetInfo, ToTransCAD.
double Pre::FSKETCHCreate2DCircleCenterPoint::_radius
Referenced by ConvertRadToDeg, GetInfo, GetRadius, ToTransCAD.
double Pre::FSKETCHCreate2DCircleCenterPoint::startAngle
Referenced by GetInfo, ToTransCAD.
double Pre::FSKETCHCreate2DCircleCenterPoint::_startAngle
double Pre::FSKETCHCreate2DCircleCenterPoint::endAngle
Referenced by GetInfo, ToTransCAD.
double Pre::FSKETCHCreate2DCircleCenterPoint::_endAngle
double Pre::FSKETCHCreate2DCircleCenterPoint::startPoint[3][3]
Referenced by ConvertRadToDeg, GetStartPoint, SetStartPoint, ToTransCAD.
double Pre::FSKETCHCreate2DCircleCenterPoint::endPoint[3][3]
Referenced by ConvertRadToDeg, GetEndPoint, SetEndPoint, ToTransCAD.
int Pre::FSKETCHCreate2DCircleCenterPoint::circleType
Referenced by GetInfo, ToTransCAD.
string Pre::FSKETCHCreate2DCircleCenterPoint::_center
Referenced by Modify.
string Pre::FSKETCHCreate2DCircleCenterPoint::_startPoint
Referenced by GetStartPointName, Modify.
string Pre::FSKETCHCreate2DCircleCenterPoint::_endPoint
Referenced by GetEndPointName, Modify.
Pre::FSKETCHCreate2DCircleCenterPoint::FSKETCHCreate2DCircleCenterPoint(FSketch *pFSketch, int type, string name)
Pre::FSKETCHCreate2DCircleCenterPoint::~FSKETCHCreate2DCircleCenterPoint(void)
void Pre::FSKETCHCreate2DCircleCenterPoint::GetCenterPoint(Point3D &cP)
References center.
Referenced by Pre::FeatureSOLIDCreateRevolve::AddNewRevolveAxis, Pre::FeatureSOLIDCreatePatternCircular::SetDirection.
double Pre::FSKETCHCreate2DCircleCenterPoint::GetRadius() const
References _radius.
void Pre::FSKETCHCreate2DCircleCenterPoint::SetStartPoint(Point3D sP)
References startPoint.
void Pre::FSKETCHCreate2DCircleCenterPoint::SetEndPoint(Point3D eP)
References endPoint.
Point3D Pre::FSKETCHCreate2DCircleCenterPoint::GetStartPoint()
References startPoint.
Point3D Pre::FSKETCHCreate2DCircleCenterPoint::GetEndPoint()
References endPoint.
string Pre::FSKETCHCreate2DCircleCenterPoint::GetStartPointName()
References _startPoint.
string Pre::FSKETCHCreate2DCircleCenterPoint::GetEndPointName()
References _endPoint.
void Pre::FSKETCHCreate2DCircleCenterPoint::GetInfo(ifstream &is)
References _radius, center, circleType, endAngle, Pre::FSketch::GetFactoryName, Pre::FSKETCHItem::GetFeatureSketch, startAngle.
void Pre::FSKETCHCreate2DCircleCenterPoint::ToTransCAD()
References Pre::FSKETCHItem::_name, _radius, center, circleType, ConvertRadToDeg, endAngle, endPoint, Pre::FSKETCHItem::GetFeatureSketch, Pre::FSketch::GetSketchEditorPtr, startAngle, startPoint.
void Pre::FSKETCHCreate2DCircleCenterPoint::Modify(char *buffer)
References _center, _endPoint, Pre::FSKETCHItem::_id, Pre::FSKETCHItem::_name, _startPoint, Pre::FSketch::AddEntityNameReportName, Pre::FSKETCHItem::GetFeatureSketch.
void Pre::FSKETCHCreate2DCircleCenterPoint::ConvertRadToDeg(double x, double y)
References _radius, center, endPoint, startPoint.
Referenced by ToTransCAD.