Post::FSketch
TransCAD::IReferencePtr Post::FSketch::_spReference
Referenced by FSketch, GetInfo.
TransCAD::IStdSketchGeometriesPtr Post::FSketch::_spGeometries
Referenced by FSketch, GetInfo, ToCATIA.
std::vector<SKETCHItem*> Post::FSketch::_sketchItemList
Referenced by Clear, CreateSketchItem, GetSketchItem, GetSketchItemsSize.
double Post::FSketch::_CSYS[9][9]
Referenced by FSketch, ToCATIA.
int Post::FSketch::_type
Referenced by GetInfo, ToCATIA.
string Post::FSketch::_refName
Referenced by GetInfo, ToCATIA.
SKETCH_INFO Post::FSketch::sInfo
Referenced by GetInfo.
bool Post::FSketch::_isInversed
Referenced by FSketch, ToCATIA.
Post::FSketch::FSketch(Part *pPart, TransCAD::IFeaturePtr spFeature)
References _CSYS, _isInversed, Post::Feature::_spFeature, _spGeometries, _spReference.
Post::FSketch::~FSketch(void)
References Clear.
void Post::FSketch::Clear()
References _sketchItemList.
Referenced by ~FSketch.
SKETCHItem* Post::FSketch::GetSketchItem(int index) const
References _sketchItemList.
Referenced by GetInfo, ToCATIA.
size_t Post::FSketch::GetSketchItemsSize() const
References _sketchItemList.
Referenced by GetInfo, Post::SKETCHItem::SKETCHItem, ToCATIA.
void Post::FSketch::GetInfo()
References _refName, _spGeometries, _spReference, _type, Post::CATIAReferenceManager::AddNewEntity, Post::CATIAReferenceManager::AddSketchInfo, CreateSketchItem, ExternMode, Post::g_pRefManager, Post::Feature::GetFeatureName, Post::SKETCHItem::GetInfo, GetSketchItem, GetSketchItemsSize, sInfo, Post::_sketchInfo::sketch_name, Post::_sketchInfo::sketch_ref.
void Post::FSketch::ToCATIA()
References _CSYS, _isInversed, Post::Feature::_pPart, _refName, Post::Part::_spFeatures, _spGeometries, _type, Post::CATIAReferenceManager::AddNewEntity, arr_index, Post::CATIAReferenceManager::ConvertToBRepFace, CreateSketchItem, Post::g_pRefManager, Post::Part::GetFeatureByName, Post::SKETCHItem::GetInfo, Post::Feature::GetPart, GetSketchItem, GetSketchItemsSize, Post::Feature::GetTransCADFeature, Post::FDatumPlaneOffset::IsBrepReference, ln_index, ref_index, sktch, Post::SKETCHItem::ToCATIA.
SKETCHItem * Post::FSketch::CreateSketchItem(TransCAD::IStdSketchGeometryPtr spItem)
References _sketchItemList.
Referenced by GetInfo, ToCATIA.