Post::SKETCHCreate2DCircularArc
string Post::SKETCHCreate2DCircularArc::TransCADName
Referenced by GetInfo, ToCATIA.
Point3D Post::SKETCHCreate2DCircularArc::_centerPoint
Referenced by GetCenterPoint, GetInfo, SetCenterPoint, ToCATIA.
Point3D Post::SKETCHCreate2DCircularArc::_startPoint
Referenced by GetInfo, GetStartPoint, SetStartPoint.
Point3D Post::SKETCHCreate2DCircularArc::_endPoint
Referenced by GetEndPoint, GetInfo, SetEndPoint.
double Post::SKETCHCreate2DCircularArc::_startAngle
Referenced by GetInfo, ToCATIA.
double Post::SKETCHCreate2DCircularArc::_endAngle
Referenced by GetInfo, ToCATIA.
double Post::SKETCHCreate2DCircularArc::_radius
Referenced by GetInfo, ToCATIA.
Post::SKETCHCreate2DCircularArc::SKETCHCreate2DCircularArc(FSketch *pFSketch, TransCAD::IStdSketchGeometryPtr spItem)
Post::SKETCHCreate2DCircularArc::~SKETCHCreate2DCircularArc(void)
void Post::SKETCHCreate2DCircularArc::SetCenterPoint(const Point3D &centerPoint)
References _centerPoint.
Referenced by GetInfo.
void Post::SKETCHCreate2DCircularArc::SetStartPoint(const Point3D &startPoint)
References _startPoint.
Referenced by GetInfo.
void Post::SKETCHCreate2DCircularArc::SetEndPoint(const Point3D &endPoint)
References _endPoint.
Referenced by GetInfo.
Point3D Post::SKETCHCreate2DCircularArc::GetCenterPoint()
References _centerPoint.
Point3D Post::SKETCHCreate2DCircularArc::GetStartPoint()
References _startPoint.
Point3D Post::SKETCHCreate2DCircularArc::GetEndPoint()
References _endPoint.
void Post::SKETCHCreate2DCircularArc::GetInfo()
References _centerPoint, _endAngle, _endPoint, Post::SKETCHItem::_pFSketch, _radius, _startAngle, _startPoint, Post::CATIAReferenceManager::AddNewEntity, ExternMode, Post::g_pRefManager, Post::Feature::GetTransCADFeature, Post::SKETCHItem::GetTransCADGeometryItem, SetCenterPoint, SetEndPoint, SetStartPoint, TransCADName.
void Post::SKETCHCreate2DCircularArc::ToCATIA()
References _centerPoint, _endAngle, Post::SKETCHItem::_pFSketch, _radius, _startAngle, Post::CATIAReferenceManager::AddNewEntity, circle_index, Post::g_pRefManager, Post::SKETCHItem::GetFeatureSketch, Post::SKETCHItem::GetSketchItemName, Post::Feature::GetTransCADFeature, sktch, TransCADName.