CATIATranslator::Form1
PartScript_Dll CATIATranslator.Form1.m_DLL
Referenced by CATIATranslator.Form1.button5_Click_1.
System.ComponentModel.IContainer CATIATranslator.Form1.components
필수 디자이너 변수입니다.
Referenced by CATIATranslator.Form1.Dispose.
System.Windows.Forms.Button CATIATranslator.Form1.button2
System.Windows.Forms.Button CATIATranslator.Form1.button1
System.Windows.Forms.Button CATIATranslator.Form1.button3
System.Windows.Forms.Button CATIATranslator.Form1.button4
System.Windows.Forms.Button CATIATranslator.Form1.button5
System.Windows.Forms.Button CATIATranslator.Form1.button6
System.Windows.Forms.Label CATIATranslator.Form1.label1
System.Windows.Forms.Label CATIATranslator.Form1.label2
System.Windows.Forms.Label CATIATranslator.Form1.label3
CATIATranslator.Form1.Form1()
References CATIATranslator.Form1.InitializeComponent.
string CATIATranslator.Form1.CATPartOpenDialog()
Referenced by CATIATranslator.Form1.button1_Click.
string CATIATranslator.Form1.CATPartSaveDialog()
Referenced by CATIATranslator.Form1.button2_Click.
string CATIATranslator.Form1.CATScriptOpenDialog()
Referenced by CATIATranslator.Form1.button3_Click_1, CATIATranslator.Form1.button5_Click_1.
string CATIATranslator.Form1.CATScriptSaveDialog()
Referenced by CATIATranslator.Form1.button4_Click_1, CATIATranslator.Form1.button6_Click_1.
string CATIATranslator.Form1.CATAssemblyOpenDialog()
string CATIATranslator.Form1.CATAssemblySaveDialog()
void CATIATranslator.Form1.button1_Click(object sender, EventArgs e)
References CATIATranslator.Form1.CATPartOpenDialog, CATIATranslator.Part.InitializeCATIA.
void CATIATranslator.Form1.button2_Click(object sender, EventArgs e)
References CATIATranslator.Form1.CATPartSaveDialog, CATIATranslator.Part.InitializeTransCAD.
void CATIATranslator.Form1.button3_Click_1(object sender, EventArgs e)
References CATIATranslator.Form1.CATScriptOpenDialog, ConstraintInfo.master_ref, ConstraintInfo.slave_ref.
void CATIATranslator.Form1.button4_Click_1(object sender, EventArgs e)
References CATIATranslator.Form1.CATScriptSaveDialog.
void CATIATranslator.Form1.button5_Click_1(object sender, EventArgs e)
References CATIATranslator.Form1.CATScriptOpenDialog, g_spApplication, CATIATranslator.Form1.m_DLL, CATIATranslator.PartScript_Dll.TransStatus.
void CATIATranslator.Form1.button6_Click_1(object sender, EventArgs e)
References CATIATranslator.Form1.CATScriptSaveDialog.
void CATIATranslator.Form1.Form1_Load(object sender, EventArgs e)
void CATIATranslator.Form1.label1_Click(object sender, EventArgs e)
void CATIATranslator.Form1.label2_Click(object sender, EventArgs e)
void CATIATranslator.Form1.label3_Click(object sender, EventArgs e)
void CATIATranslator.Form1.InitializeComponent()
디자이너 지원에 필요한 메서드입니다. 이 메서드의 내용을 코드 편집기로 수정하지 마십시오.
Referenced by CATIATranslator.Form1.Form1.
override void CATIATranslator.Form1.Dispose(bool disposing)
사용 중인 모든 리소스를 정리합니다.
disposing 관리되는 리소스를 삭제해야 하면 true이고, 그렇지 않으면 false입니다.
References CATIATranslator.Form1.components.