CATIATranslator::AssemblyPartManager
string CATIATranslator.AssemblyPartManager.path
Referenced by CATIATranslator.AssemblyPartManager.AssemblyPartManager, CATIATranslator.AssemblyPartManager.button2_Click, CATIATranslator.AssemblyPartManager.button3_Click, CATIATranslator.AssemblyPartManager.button4_Click, CATIATranslator.AssemblyPartManager.Updatelist.
string CATIATranslator.AssemblyPartManager.fullpath
Referenced by CATIATranslator.AssemblyPartManager.AssemblyPartManager, CATIATranslator.AssemblyPartManager.button2_Click, CATIATranslator.AssemblyPartManager.button3_Click.
Assembly CATIATranslator.AssemblyPartManager.AssemblyManager
Referenced by CATIATranslator.AssemblyPartManager.AssemblyPartManager.
TransCAD.Assem CATIATranslator.AssemblyPartManager._tAssem
Referenced by CATIATranslator.AssemblyPartManager.AssemblyPartManager.
System.ComponentModel.IContainer CATIATranslator.AssemblyPartManager.components
Required designer variable.
Referenced by CATIATranslator.AssemblyPartManager.Dispose.
System.Windows.Forms.ListView CATIATranslator.AssemblyPartManager.listView1
Referenced by CATIATranslator.AssemblyPartManager.button2_Click, CATIATranslator.AssemblyPartManager.button3_Click, CATIATranslator.AssemblyPartManager.button4_Click, CATIATranslator.AssemblyPartManager.Updatelist.
System.Windows.Forms.ColumnHeader CATIATranslator.AssemblyPartManager.PartName
System.Windows.Forms.ColumnHeader CATIATranslator.AssemblyPartManager.CatScripts
System.Windows.Forms.ColumnHeader CATIATranslator.AssemblyPartManager.CatParts
System.Windows.Forms.Label CATIATranslator.AssemblyPartManager.label1
System.Windows.Forms.Button CATIATranslator.AssemblyPartManager.button1
System.Windows.Forms.Button CATIATranslator.AssemblyPartManager.button2
System.Windows.Forms.Button CATIATranslator.AssemblyPartManager.button3
System.Windows.Forms.Button CATIATranslator.AssemblyPartManager.button4
CATIATranslator.AssemblyPartManager.AssemblyPartManager(string filePath)
References CATIATranslator.AssemblyPartManager._tAssem, CATIATranslator.AssemblyPartManager.AssemblyManager, CATIATranslator.AssemblyPartManager.fullpath, CATIATranslator.AssemblyPartManager.InitializeComponent, CATIATranslator.AssemblyPartManager.path, CATIATranslator.Assembly.tAssemDoc, CATIATranslator.AssemblyPartManager.Updatelist.
void CATIATranslator.AssemblyPartManager.Updatelist()
References CATIATranslator.AssemblyPartManager.listView1, CATIATranslator.AssemblyPartManager.path.
Referenced by CATIATranslator.AssemblyPartManager.AssemblyPartManager, CATIATranslator.AssemblyPartManager.button1_Click, CATIATranslator.AssemblyPartManager.button2_Click, CATIATranslator.AssemblyPartManager.button4_Click.
void CATIATranslator.AssemblyPartManager.button1_Click(object sender, EventArgs e)
References CATIATranslator.AssemblyPartManager.Updatelist.
void CATIATranslator.AssemblyPartManager.button2_Click(object sender, EventArgs e)
References CATIATranslator.AssemblyPartManager.fullpath, CATIATranslator.AssemblyPartManager.listView1, CATIATranslator.AssemblyPartManager.path, CATIATranslator.AssemblyPartManager.Updatelist.
void CATIATranslator.AssemblyPartManager.button4_Click(object sender, EventArgs e)
References CATIATranslator.AssemblyPartManager.listView1, CATIATranslator.AssemblyPartManager.path, CATIATranslator.AssemblyPartManager.Updatelist.
void CATIATranslator.AssemblyPartManager.button3_Click(object sender, EventArgs e)
References CATIATranslator.AssemblyPartManager.fullpath, CATIATranslator.AssemblyPartManager.listView1, CATIATranslator.AssemblyPartManager.path.
void CATIATranslator.AssemblyPartManager.InitializeComponent()
Required method for Designer support - do not modify the contents of this method with the code editor.
Referenced by CATIATranslator.AssemblyPartManager.AssemblyPartManager.
override void CATIATranslator.AssemblyPartManager.Dispose(bool disposing)
Clean up any resources being used.
disposing true if managed resources should be disposed; otherwise, false.
References CATIATranslator.AssemblyPartManager.components.