Post::CATIAReferenceManager
int Post::CATIAReferenceManager::_id
Referenced by AddNewEntity, CATIAReferenceManager.
std::vector<POINTNAME_MAP> Post::CATIAReferenceManager::_listPointNameMap
Referenced by AddNewPointName, GetCatiaPointNameByTransCADPointName.
std::vector<ENTITY_MAP> Post::CATIAReferenceManager::_listEntityNameMap
Referenced by AddNewEntity, GetEntityIDByTransCADName, GetTransCADNameByEntityID.
std::vector<int> Post::CATIAReferenceManager::_listEntityID
Referenced by AddNewEntity.
std::vector<std::string> Post::CATIAReferenceManager::_listTransCADName
Referenced by AddNewEntity.
std::vector<NAME_MAP> Post::CATIAReferenceManager::_listNameMap
Referenced by AddNewFeature, GetFeatureIDByTransCADName, GetFeatureTypeByTransCADName.
std::vector<SKETCH_INFO> Post::CATIAReferenceManager::_listSketchInfo
Referenced by AddSketchInfo.
Post::CATIAReferenceManager::CATIAReferenceManager(void)
References _id.
Post::CATIAReferenceManager::~CATIAReferenceManager(void)
int Post::CATIAReferenceManager::AddNewEntity(std::string strSketchName, std::string strTransCADName)
References Post::_tagEntityMap::_entityName, _id, _listEntityID, _listEntityNameMap, _listTransCADName, Post::_tagEntityMap::_sketchName, Post::_tagEntityMap::id.
Referenced by Post::SKETCHCreate2DCenterline::GetInfo, Post::SKETCHCreate2DPoint::GetInfo, Post::FSketch::GetInfo, Post::SKETCHCreate2DLine2Points::GetInfo, Post::SKETCHCreate2DCircleCenterPoint::GetInfo, Post::SKETCHCreate2DCircularArc::GetInfo, Post::SKETCHCreate2DCenterline::ToCATIA, Post::SKETCHCreate2DPoint::ToCATIA, Post::FSketch::ToCATIA, Post::SKETCHCreate2DCircleCenterPoint::ToCATIA, Post::SKETCHCreate2DLine2Points::ToCATIA, Post::SKETCHCreate2DCircularArc::ToCATIA.
int Post::CATIAReferenceManager::AddNewFeature(TransCAD::IFeaturePtr spFeature)
References Post::_tagNameMap::_id, _listNameMap, Post::_tagNameMap::_name, Post::_tagNameMap::_type.
Referenced by Post::Part::CreateFeature.
int Post::CATIAReferenceManager::GetFeatureIDByTransCADName(std::string strTransCADName, int &id)
References _listNameMap.
Referenced by ConvertToBRepEdge, ConvertToBRepFace, ConvertToBRepFaceForDatumPlane, ConvertToBRepFaceForHole, GetBasicNameOfCATIA, Post::FeatureSOLIDCreatePatternCircular::GetInfo, Post::FeatureSOLIDCreatePatternRectangular::GetInfo, Post::FeatureSOLIDCreateFilletConstant::ToCATIA, Post::FeatureSOLIDCreatePatternCircular::ToCATIA, Post::FeatureSOLIDCreatePatternRectangular::ToCATIA, Post::FDatumPlaneOffset::ToCATIA, Post::FeatureSOLIDCreateChamfer::ToCATIA, Post::FeatureSOLIDCreateCutRevolve::ToCATIA, Post::FeatureSOLIDCreateCutExtrude::ToCATIA, Post::FeatureSOLIDCreateProtrusionExtrude::ToCATIA, Post::FeatureSOLIDCreateProtrusionRevolve::ToCATIA, Post::FeatureSOLIDCreateProtrusionLoft::ToCATIA, Post::FeatureSOLIDCreateSectionsLoft::ToCATIA, Post::FeatureSOLIDCreateFacesLoft::ToCATIA, Post::FeatureSOLIDCreateProtrusionSweep::ToCATIA.
int Post::CATIAReferenceManager::GetFeatureTypeByTransCADName(std::string strTransCADName, TransCAD::FeatureType &type)
References _listNameMap.
Referenced by ConvertToBRepEdge, ConvertToBRepFace, ConvertToBRepFaceForDatumPlane, ConvertToBRepFaceForHole, GetBasicNameOfCATIA, Post::FeatureSOLIDCreatePatternRectangular::GetInfo, Post::FeatureSOLIDCreatePatternCircular::GetInfo, GetReferenceeFeature.
std::string Post::CATIAReferenceManager::FeatureTypeToString(TransCAD::FeatureType type)
Referenced by ConvertToBRepEdge, ConvertToBRepFace, ConvertToBRepFaceForDatumPlane, ConvertToBRepFaceForHole, GetBasicNameOfCATIA, Post::FeatureSOLIDCreatePatternRectangular::GetInfo, Post::FeatureSOLIDCreatePatternCircular::GetInfo, GetReferenceeFeature.
std::string Post::CATIAReferenceManager::ConvertToBRepFace(std::string strPersistentName)
References Post::EN_F::_bn, Post::secondary_name::_bn_list, Post::EN_F::_sn, Post::basic_naming::feature_id, FeatureTypeToString, GetFaceNameOfCATIA, GetFeatureIDByTransCADName, GetFeatureTypeByTransCADName, Post::Parsing_F, Post::secondary_name::total_num.
Referenced by ReferenceClass::ref_Post::T2C_ReferenceName_From_Part, Post::FSketch::ToCATIA.
std::string Post::CATIAReferenceManager::ConvertToBRepFaceForHole(std::string strPersistentName)
References Post::EN_F::_bn, Post::secondary_name::_bn_list, Post::EN_F::_sn, Post::basic_naming::feature_id, FeatureTypeToString, GetFaceNameOfCATIA, GetFeatureIDByTransCADName, GetFeatureTypeByTransCADName, Post::Parsing_F, Post::secondary_name::total_num.
Referenced by Post::FeatureSOLIDCreateHoleCounterbored::ToCATIA, Post::FeatureSOLIDCreateHoleCountersunk::ToCATIA.
std::string Post::CATIAReferenceManager::ConvertToBRepFaceForDatumPlane(std::string strPersistentName)
References Post::EN_F::_bn, Post::secondary_name::_bn_list, Post::EN_F::_sn, Post::basic_naming::feature_id, FeatureTypeToString, GetFaceNameOfCATIA, GetFeatureIDByTransCADName, GetFeatureTypeByTransCADName, Post::Parsing_F, Post::secondary_name::total_num.
Referenced by Post::FDatumPlaneOffset::ToCATIA.
std::string Post::CATIAReferenceManager::ConvertToBRepEdge(std::string strPersistentName)
References Post::EN_F::_bn, Post::secondary_name::_bn_list, Post::EN_E::_f1, Post::EN_E::_f2, Post::EN_F::_sn, Post::basic_naming::feature_id, FeatureTypeToString, GetFaceNameOfCATIA, GetFeatureIDByTransCADName, GetFeatureTypeByTransCADName, Post::Parsing_E, Post::secondary_name::total_num.
Referenced by Post::FeatureSOLIDCreateChamfer::ToCATIA, Post::FeatureSOLIDCreateFilletConstant::ToCATIA.
void Post::CATIAReferenceManager::AddNewPointName(std::string strSketchName, std::string CATIApointName, std::string TransCADpointName)
References Post::_tagpointNameMap::_CATIAName, _listPointNameMap, Post::_tagpointNameMap::_sketchName, Post::_tagpointNameMap::_TransCADName.
Referenced by Post::SKETCHCreate2DPoint::ToCATIA.
std::string Post::CATIAReferenceManager::GetCatiaPointNameByTransCADPointName(std::string strSketchName, std::string TransCADpointName)
References _listPointNameMap.
Referenced by Post::SKETCHCreate2DLine2Points::GetInfo.
void Post::CATIAReferenceManager::AddSketchInfo(SKETCH_INFO _sInfo)
References _listSketchInfo.
Referenced by Post::FSketch::GetInfo.
void Post::CATIAReferenceManager::eew()
int Post::CATIAReferenceManager::GetTransCADNameByEntityID(std::string strSketchName, int id, std::string &strTransCADName)
References _listEntityNameMap.
int Post::CATIAReferenceManager::GetEntityIDByTransCADName(std::string strSketchName, std::string strTransCADName, int &id)
References _listEntityNameMap.
Referenced by GetBasicNameOfCATIA.
std::string Post::CATIAReferenceManager::GetFaceNameOfCATIA(EN_F faceName)
References Post::EN_F::_bn, Post::secondary_name::_bn_list, Post::EN_F::_sn, GetBasicNameOfCATIA, Post::secondary_name::total_num.
Referenced by ConvertToBRepEdge, ConvertToBRepFace, ConvertToBRepFaceForDatumPlane, ConvertToBRepFaceForHole.
std::string Post::CATIAReferenceManager::GetBasicNameOfCATIA(basic_naming basicName)
References Post::basic_naming::feature_id, FeatureTypeToString, GetEntityIDByTransCADName, GetFeatureIDByTransCADName, GetFeatureTypeByTransCADName, Post::basic_naming::id1, Post::basic_naming::id2, Post::basic_naming::id3, Post::basic_naming::id4.
Referenced by GetFaceNameOfCATIA.
std::string Post::CATIAReferenceManager::GetReferenceeFeature(std::string strPersistentName)
References Post::EN_F::_bn, Post::basic_naming::feature_id, FeatureTypeToString, GetFeatureTypeByTransCADName, Post::Parsing_F.