Pre::FSKETCHItem
FSketch* Pre::FSKETCHItem::_pFSketch
Referenced by FSKETCHItem, GetFeatureSketch.
string Pre::FSKETCHItem::_name
Referenced by FSKETCHItem, GetSketchItemName, Pre::FSKETCHCreate2DPoint::Modify, Pre::FSKETCHCreate2DLine2Points::Modify, Pre::FSKETCHCreate2DCircleCenterPoint::Modify, Pre::FSKETCHCreate2DLine2Points::ToTransCAD, Pre::FSKETCHCreate2DCircleCenterPoint::ToTransCAD.
int Pre::FSKETCHItem::_type
Referenced by FSKETCHItem, GetSketchItemType.
int Pre::FSKETCHItem::_id
Referenced by Pre::FSKETCHCreate2DPoint::Modify, Pre::FSKETCHCreate2DLine2Points::Modify, Pre::FSKETCHCreate2DCircleCenterPoint::Modify.
int Pre::FSKETCHItem::_centerLineInfo
Referenced by FSKETCHItem, SetCenterLineInfo, Pre::FSKETCHCreate2DLine2Points::ToTransCAD.
Pre::FSKETCHItem::FSKETCHItem(FSketch *pFSketch, int type, string name)
References _centerLineInfo, _name, _pFSketch, _type.
Pre::FSKETCHItem::~FSKETCHItem(void)
FSketch* Pre::FSKETCHItem::GetFeatureSketch()
References _pFSketch.
Referenced by Pre::FSKETCHCreate2DCircleCenterPoint::GetInfo, Pre::FSKETCHCreate2DPoint::Modify, Pre::FSKETCHCreate2DLine2Points::Modify, Pre::FSKETCHCreate2DCircleCenterPoint::Modify, Pre::FSKETCHCreate2DLine2Points::ToTransCAD, Pre::FSKETCHCreate2DCircleCenterPoint::ToTransCAD.
string Pre::FSKETCHItem::GetSketchItemName()
References _name.
int Pre::FSKETCHItem::GetSketchItemType()
References _type.
void Pre::FSKETCHItem::SetCenterLineInfo(int centerLineInfo)
References _centerLineInfo.
Referenced by Pre::FSketch::GetSketchItemInfo.
void Pre::FSKETCHItem::GetInfo(ifstream &is)
Referenced by Pre::FSketch::CreateSketchItem.
void Pre::FSKETCHItem::ToTransCAD()
Referenced by Pre::FSketch::ToTransCAD.
void Pre::FSKETCHItem::Modify(char *buffer)
Referenced by Pre::FSketch::GetSketchItemInfo.