Post
LimitMode
selection_type
bn_option
typedef struct Post::_tagNameMap Post::NAME_MAP
typedef struct Post::_tagEntityMap Post::ENTITY_MAP
typedef struct Post::_tagpointNameMap Post::POINTNAME_MAP
typedef struct Post::_sketchInfo Post::SKETCH_INFO
typedef class Vector3D Post::Point3D
typedef class Vector3D Post::Direct3D
TransCAD::IApplicationPtr Post::g_spApplication
Referenced by CATIAPostStartService, CATIAPostTranslate, Post::Part::~Part.
CATIAReferenceManager * Post::g_pRefManager
Referenced by ReferenceClass::ref_Post::AssemblyPartT2C, CATIAPostStartService, CATIAPostTranslate, Post::Part::CreateFeature, Post::FeatureSOLIDCreatePatternCircular::GetInfo, Post::FeatureSOLIDCreatePatternRectangular::GetInfo, Post::SKETCHCreate2DCenterline::GetInfo, Post::SKETCHCreate2DPoint::GetInfo, Post::FSketch::GetInfo, Post::SKETCHCreate2DCircleCenterPoint::GetInfo, Post::SKETCHCreate2DLine2Points::GetInfo, Post::SKETCHCreate2DCircularArc::GetInfo, ReferenceClass::ref_Post::T2C_ReferenceName_From_Part, Post::FeatureSOLIDCreateHoleCounterbored::ToCATIA, Post::FeatureSOLIDCreatePatternRectangular::ToCATIA, Post::FeatureSOLIDCreateFilletConstant::ToCATIA, Post::FDatumPlaneOffset::ToCATIA, Post::FeatureSOLIDCreateHoleCountersunk::ToCATIA, Post::FeatureSOLIDCreateChamfer::ToCATIA, Post::FeatureSOLIDCreatePatternCircular::ToCATIA, Post::FeatureSOLIDCreateCutRevolve::ToCATIA, Post::FeatureSOLIDCreateProtrusionExtrude::ToCATIA, Post::FeatureSOLIDCreateProtrusionRevolve::ToCATIA, Post::FeatureSOLIDCreateCutExtrude::ToCATIA, Post::FeatureSOLIDCreateSectionsLoft::ToCATIA, Post::FeatureSOLIDCreateFacesLoft::ToCATIA, Post::FeatureSOLIDCreateProtrusionSweep::ToCATIA, Post::FeatureSOLIDCreateProtrusionLoft::ToCATIA, Post::SKETCHCreate2DCenterline::ToCATIA, Post::SKETCHCreate2DPoint::ToCATIA, Post::FSketch::ToCATIA, Post::SKETCHCreate2DCircleCenterPoint::ToCATIA, Post::SKETCHCreate2DLine2Points::ToCATIA, Post::SKETCHCreate2DCircularArc::ToCATIA.
DLLCATIAPOST_API int Post::CATIAPostStartService()
References g_pRefManager, g_spApplication.
DLLCATIAPOST_API int Post::CATIAPostTranslate(char argv[])
References ang_index, arr_index, circle_index, DatumPlaneID, fac_index, g_pRefManager, g_spApplication, Post::Part::GetInfo, holecounterID, lim_index, ln_index, lng_index, pt_index, ref_index, repname_index, sktch, Post::Part::ToCATIA.
void Post::Parsing_F(string _str, EN_F &_f)
References Post::EN_F::_bn, Post::EN_F::_osi, Post::EN_F::_sn, Delim_F, Parsing_BN, Parsing_OSI, Parsing_SN.
Referenced by Post::CATIAReferenceManager::ConvertToBRepFace, Post::CATIAReferenceManager::ConvertToBRepFaceForDatumPlane, Post::CATIAReferenceManager::ConvertToBRepFaceForHole, Post::CATIAReferenceManager::GetReferenceeFeature, Parsing_E, Parsing_V.
void Post::Parsing_E(string str, EN_E &e)
References Post::EN_E::_f1, Post::EN_E::_f2, Delim_E, Parsing_F.
Referenced by Post::CATIAReferenceManager::ConvertToBRepEdge.
void Post::Parsing_V(string str, EN_V &v)
References Post::EN_V::_f1, Post::EN_V::_f2, Post::EN_V::_f3, Post::EN_V::_osi, Delim_V, Parsing_F, Parsing_OSI.
void Post::Parsing_BN(string _str, basic_naming &_bn)
References ChamferFeature, DatumFeature, ExtrudeFeature, Post::basic_naming::feature_id, FilletFeature, Post::basic_naming::id1, Post::basic_naming::id2, Post::basic_naming::id3, Post::basic_naming::id4, Post::basic_naming::id5, LoftFeature, Post::basic_naming::option, PatternFeature, RevolveFeature, ShellFeature, Sketch_Segment, SweepFeature.
Referenced by Parsing_F, Parsing_SN.
void Post::Parsing_OSI(string _str, OSI &_osi)
References Post::OSI::order, Post::OSI::total_num.
Referenced by Parsing_F, Parsing_V.
void Post::Parsing_SN(string _str, secondary_name &_sn)
References Post::secondary_name::_bn_list, Parsing_BN, Post::secondary_name::total_num.
Referenced by Parsing_F.
void Post::Delim_V(string _input, string &_F1, string &_F2, string &_F3, string &_OSI)
Referenced by Parsing_V.
void Post::Delim_E(string _input, string &_F1, string &_F2, string &_OSI)
Referenced by Parsing_E.
void Post::Delim_F(string _input, string &_bn, string &_OSI, string &_sn)
Referenced by Parsing_F.
string Post::Print_BN(basic_naming bn)
References Post::basic_naming::feature_id, Post::basic_naming::id1, Post::basic_naming::id2, Post::basic_naming::id3, Post::basic_naming::id4, Post::basic_naming::id5, Post::basic_naming::option.
Referenced by Print_F, Print_SN.
string Post::Print_OSI(OSI osi)
References Post::OSI::order, Post::OSI::total_num.
Referenced by Print_E, Print_F, Print_V.
string Post::Print_SN(secondary_name sn)
References Post::secondary_name::_bn_list, Print_BN, Post::secondary_name::total_num.
Referenced by Print_F.
string Post::Print_F(EN_F f)
References Post::EN_F::_bn, Post::EN_F::_osi, Post::EN_F::_sn, Print_BN, Print_OSI, Print_SN.
Referenced by Print_E, Print_V.
string Post::Print_E(EN_E e)
References Post::EN_E::_f1, Post::EN_E::_f2, Post::EN_E::_osi, Print_F, Print_OSI.
string Post::Print_V(EN_V v)
References Post::EN_V::_f1, Post::EN_V::_f2, Post::EN_V::_f3, Post::EN_V::_osi, Print_F, Print_OSI.